using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ZomboForm
{
    public class ItemSpawner
    {
        public string Id { get; set; }
        public string Icon { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public static List<ItemSpawner> myList;
        private static readonly Lazy<ItemSpawner> _instance = new Lazy<ItemSpawner>(() => new ItemSpawner());
        public static ItemSpawner Instance => _instance.Value;
        
        public ItemSpawner()
        {
        
        }
        
        public ItemSpawner(string id, string icon, string name, string description)
        {
            Id = id;
            Icon = icon;
            Name = name;
            Description = description;
        }

        public List<ItemSpawner> InitItemSpawner()
        {
             var lst = new List<ItemSpawner> {
             new ItemSpawner("unknown", "", "Unknown", @""),
             new ItemSpawner("torch", "", "Torch", @"Tool efficiency: 100%"),
             new ItemSpawner("hand_tool", "", "Hands", @""),
             new ItemSpawner("candle", "", "Candle", @""),
             new ItemSpawner("skull_candle", "", "Skull candle", @""),
             new ItemSpawner("priest_cloth", "", "Priest clothes", @""),
             new ItemSpawner("toilet_paper", "", "Toilet paper", @""),
             new ItemSpawner("barrel", "", "Barrel", @""),
             new ItemSpawner("barrel2", "", "Barrel II", @""),
             new ItemSpawner("grave_place", "", "Gravesite", @""),
             new ItemSpawner("sandwich", "", "Sandwich", @""),
             new ItemSpawner("bob_hat", "", "bob_hat", @""),
             new ItemSpawner("freshener", "i_flask_freshener", "Freshener", @""),
             new ItemSpawner("soap_pinc", "", "Pink soap", @""),
             new ItemSpawner("aromatizer", "i_flask_aromatizer", "Aromatizer", @""),
             new ItemSpawner("parfum_1", "", "Perfume", @""),
             new ItemSpawner("thread_1", "", "Thread", @""),
             new ItemSpawner("key_cmmn_1", "", "Metal key", @""),
             new ItemSpawner("key_cmmn_3", "", "Metal key", @""),
             new ItemSpawner("key_gold_1", "", "Gold key", @""),
             new ItemSpawner("key_gold_2", "", "Gold key", @""),
             new ItemSpawner("key_gold_3", "", "Gold key", @""),
             new ItemSpawner("key_silv_1", "", "Silver key", @""),
             new ItemSpawner("key_silv_2", "", "Silver key", @""),
             new ItemSpawner("key_silv_3", "", "Silver key", @""),
             new ItemSpawner("communion_cookies", "i_communion_cookie", "Communion cookies", @"Effect on use: [c][3897FF]+(en)1[-][/c]"),
             new ItemSpawner("fire", "", "fire", @""),
             new ItemSpawner("science", "", "Science", @""),
             new ItemSpawner("marketing_point", "i_horn", "Fame", @""),
             new ItemSpawner("working_zombie_pseudoitem_1", "i_2h_zombie", "working_zombie_pseudoitem_1", @""),
             new ItemSpawner("working_zombie_on_ground_1", "i_2h_zombie_drop", "working_zombie_on_ground_1", @""),
             new ItemSpawner("worker_invisible_overhead", "", "worker_invisible_overhead", @""),
             new ItemSpawner("worker_invisible_ground", "", "worker_invisible_ground", @""),
             new ItemSpawner("porter_backpack", "i_wood", "porter_backpack", @""),
             new ItemSpawner("bartender_doll", "i_2h_bartender_doll_drop", "Barmаn doll", @""),
             new ItemSpawner("tavern_reputation_item", "i_tavern_reputation", "Reputation star", @""),
             new ItemSpawner("insertion_button_pseudoitem", "i_plus", "Insert", @""),
             new ItemSpawner("blessing_commerce", "i_scroll_3", "Blessing of commerce", @"Can be sold to a vendor to increase his tier progression."),
             new ItemSpawner("bs_letter", "", "Letter to the blacksmith", @""),
             new ItemSpawner("scroll_garden_prop", "", "Garden certificate", @""),
             new ItemSpawner("scroll_graveyard_prop", "i_scroll_1", "Graveyard scroll", @"Used to open the western side of the graveyard."),
             new ItemSpawner("town_pass", "i_scroll_yellow", "Town pass", @""),
             new ItemSpawner("stamp", "", "Stamp", @""),
             new ItemSpawner("quest_key_astrologer", "i_key_cmmn_1", "Keepers key", @""),
             new ItemSpawner("quest_instruction_snake", "i_scroll_blue_bp", "Instructions for the key", @"You need to use a [c][bb5c1c]Keeper's Key[-][/c] with this instruction at a [c][bb5c1c]Study Table[-][/c]."),
             new ItemSpawner("quest_fake_coins", "i_coins", "Fake coins", @""),
             new ItemSpawner("ques_key_cultist", "i_key_gold_1", "Active key", @""),
             new ItemSpawner("bishop_license", "i_scroll_red", "Upgrade license", @""),
             new ItemSpawner("merchant_traide_license", "i_scroll_gold", "Trade license", @""),
             new ItemSpawner("quest_cultit_book", "i_journal_keeper", "Keepers diary", @""),
             new ItemSpawner("hiccup_grass", "i_flw_highlander", "Hiccup-grass", @""),
             new ItemSpawner("necklace", "i_ruby_necklace", "Necklace", @""),
             new ItemSpawner("necronomicon", "", "Necronomicon", @""),
             new ItemSpawner("restoration_instrument", "", "Restoration Tools", @""),
             new ItemSpawner("aristocrat_paper", "i_scroll_triforce_gold", "Aristocrat Papers", @""),
             new ItemSpawner("alice_paper", "i_scroll_white_graph_1", "Alisa's Paper", @""),
             new ItemSpawner("actors_song", "i_scroll_music", "Song Lyrics", @""),
             new ItemSpawner("calculation_for_mill_fix", "i_scroll_blue_bp", "Paper with Calculations", @""),
             new ItemSpawner("infusion", "i_bottle_booz_agaric", "Infusion", @"Effect on use: [c][F4203F]-(hp)20[-][/c] [c][3897FF]+(en)80[-][/c]"),
             new ItemSpawner("mirror_of_pride", "i_pocket_mirror", "Mirror of Pride", @""),
             new ItemSpawner("fork_salty", "i_fork_black", "Salty Fork", @""),
             new ItemSpawner("eternal_burning_coil", "i_ember", "Eternal Burning Coal", @""),
             new ItemSpawner("sextant", "i_goniometer", "Golden Angle", @""),
             new ItemSpawner("endless_book", "i_book_infinity", "Endless Notebook", @""),
             new ItemSpawner("hunters_medallion", "i_punchclub_amulet", "Hunter's Medallion", @""),
             new ItemSpawner("golden_apple", "i_apple_gold_crop", "Golden Apple", @""),
             new ItemSpawner("accepted_invitation", "i_scroll_white_graph_3", "Accepted invitation", @""),
             new ItemSpawner("picnic_basket", "", "Basket of food", @""),
             new ItemSpawner("huge_carrot", "i_2h_carrot_big", "huge_carrot", @""),
             new ItemSpawner("millers_invitation", "i_scroll_yellow", "Invitation to Comedy Show", @""),
             new ItemSpawner("dagger_baron", "i_tr_dagger_new", "Rare dagger", @""),
             new ItemSpawner("honey_plaster", "i_patch_honey", "Honey patch", @""),
             new ItemSpawner("honey_barrel", "i_honey_1", "A barrel of honey", @""),
             new ItemSpawner("curtain_blue", "i_curtain_blue", "Curtain", @""),
             new ItemSpawner("roof_tile", "i_roof_tile", "Roof tile", @""),
             new ItemSpawner("obsidian_research", "i_scroll_bp", "Research obsidian", @""),
             new ItemSpawner("scroll_for_hunchback", "i_scroll_blue", "A scroll with a spell", @""),
             new ItemSpawner("pie_with_poison", "i_pie", "Cake with bee poison", @""),
             new ItemSpawner("vases_with_poison", "i_vases_poison", "Vases of poison", @""),
             new ItemSpawner("rat_for_dig", "i_rat_white", "Rat", @""),
             new ItemSpawner("rand_alchemy_unlock", "i_scroll_red", "Alchemy recipe", @""),
             new ItemSpawner("rat:rat_in_jar_0", "i_rat_white", "Usual rat", @""),
             new ItemSpawner("rat:rat_in_jar_1", "i_rat_mickey", "Mickey the rat", @""),
             new ItemSpawner("rat:rat_in_jar_2", "i_rat_django", "Django the rat", @""),
             new ItemSpawner("rat:rat_in_jar_3", "i_rat_pecos", "Pecos the rat", @""),
             new ItemSpawner("rat:rat_in_jar_4", "i_rat_remy", "Remy the Rat", @""),
             new ItemSpawner("rat:rat_in_jar_5", "i_rat_splinter", "Splinter", @""),
             new ItemSpawner("rat_status:satisfied", "i_tr_red_eye", "Satisfied", @""),
             new ItemSpawner("rat_status:normal", "i_tr_flask", "Normal", @""),
             new ItemSpawner("rat_status:hungry", "i_tr_door_hinge", "Hungry", @""),
             new ItemSpawner("rat_status:very_hungry", "i_tr_helmet", "Very hungry", @""),
             new ItemSpawner("rat_status:critically_hungry", "i_tr_picklock", "Critically hungry", @""),
             new ItemSpawner("rat_buff:speed_training_1", "i_tr_medallion", "Speed training I", @""),
             new ItemSpawner("rat_buff:speed_training_2", "i_tr_dagger", "Speed training II", @""),
             new ItemSpawner("rat_buff:speed_training_3", "i_tr_buckle", "Speed training III", @""),
             new ItemSpawner("rat_buff:dog_training_1", "i_tr_clay_shards", "Dog training I", @""),
             new ItemSpawner("rat_buff:dog_training_2", "i_tr_red_eye_amulet", "Dog training II", @""),
             new ItemSpawner("rat_buff:dog_training_3", "i_tr_handcuff", "Dog training III", @""),
             new ItemSpawner("rat_buff:fast", "i_tr_pickaxe", "rat_buff:fast", @""),
             new ItemSpawner("rat_buff:obedient", "i_tr_key", "rat_buff:obedient", @""),
             new ItemSpawner("tr_red_eye", "i_tr_red_eye", "Statuette of the Ancient God", @""),
             new ItemSpawner("tr_flask", "i_tr_flask", "Ancient wine flask", @""),
             new ItemSpawner("tr_door_hinge", "i_tr_door_hinge", "Ancient door hinge", @""),
             new ItemSpawner("tr_helmet", "i_tr_helmet", "Legionary helm", @""),
             new ItemSpawner("tr_picklock", "i_tr_picklock", "Ancient lock pick", @""),
             new ItemSpawner("tr_medallion", "i_tr_medallion", "Priest's medallion", @""),
             new ItemSpawner("tr_dagger", "i_tr_dagger", "Legionary dagger", @""),
             new ItemSpawner("tr_buckle", "i_tr_buckle", "Ancient belt buckle", @""),
             new ItemSpawner("tr_clay_shards", "i_tr_clay_shards", "Clay shards of an ancient vase", @""),
             new ItemSpawner("tr_red_eye_amulet", "i_tr_red_eye_amulet", "Amulet of the Ancient God", @""),
             new ItemSpawner("tr_handcuff", "i_tr_handcuff", "Ancient shackles", @""),
             new ItemSpawner("tr_pickaxe", "i_tr_pickaxe", "Ancient pickaxe", @""),
             new ItemSpawner("tr_key", "i_tr_key", "Ancient keys to the prison cell", @""),
             new ItemSpawner("tr_resin_pot", "i_tr_resin_pot", "Clay pot of tar", @""),
             new ItemSpawner("tr_bellas_ring", "i_tr_bellas_ring", "Priestess' Ring", @""),
             new ItemSpawner("tr_signet", "i_tr_signet", "Priest's signet", @""),
             new ItemSpawner("tr_brick", "i_tr_brick", "Brick from the Church", @""),
             new ItemSpawner("candle_1", "", "Candle", @""),
             new ItemSpawner("candle_2", "", "Candle", @""),
             new ItemSpawner("candle_3", "", "Candle", @""),
             new ItemSpawner("candle_4", "", "Candle", @""),
             new ItemSpawner("candle_6", "", "Candle", @""),
             new ItemSpawner("incense_1", "", "Incense", @""),
             new ItemSpawner("incense_2", "", "Incense II", @""),
             new ItemSpawner("silk", "", "Silk", @""),
             new ItemSpawner("faith", "", "Faith", @"You can call it faith, inspiration, self-confidence. Anyway it's as powerful as money."),
             new ItemSpawner("fruit:berry", "i_berry", "Berry", @"Effect on use: [c][3897FF]+(en)5[-][/c]"),
             new ItemSpawner("fruit:apple_green_crop", "i_apple_green_crop", "Green apple", @"Effect on use: [c][3897FF]+(en)5[-][/c]"),
             new ItemSpawner("fruit:apple_red_crop", "i_apple_red_crop", "Red apple", @"Effect on use: [c][3897FF]+(en)5[-][/c]"),
             new ItemSpawner("honey", "", "Honey", @"Effect on use: [c][F4203F]+(hp)3[-][/c] [c][3897FF]+(en)25[-][/c]"),
             new ItemSpawner("beeswax", "", "Beeswax", @""),
             new ItemSpawner("ash", "", "Ash", @""),
             new ItemSpawner("shr_agaric", "", "Red mushroom", @"Effect on use: [c][F4203F]-(hp)5[-][/c]"),
             new ItemSpawner("shr_boletus", "", "Edible mushroom", @"Effect on use: [c][F4203F]-(hp)1[-][/c] [c][3897FF]+(en)5[-][/c]"),
             new ItemSpawner("wheat_seed", "i_wheat_seed", "Wheat seed", @""),
             new ItemSpawner("wheat_crop", "i_wheat_crop", "Wheat", @""),
             new ItemSpawner("cabbage_seed", "i_cabbage_seed", "Cabbage seed", @""),
             new ItemSpawner("cabbage_crop", "i_cabbage_crop", "Cabbage", @"Effect on use: [c][3897FF]+(en)5[-][/c]"),
             new ItemSpawner("carrot_seed", "i_carrot_seed", "Carrot seed", @""),
             new ItemSpawner("carrot_crop", "i_carrot_crop", "Carrot", @"Effect on use: [c][3897FF]+(en)5[-][/c]"),
             new ItemSpawner("beet_seed", "i_beet_seed", "Beet seed", @""),
             new ItemSpawner("beet_crop", "i_beet_crop", "Beet", @"Effect on use: [c][3897FF]+(en)8[-][/c]"),
             new ItemSpawner("onion_seed:1", "i_onion_seed", "Onion seed", @""),
             new ItemSpawner("onion_seed:2", "i_onion_seed", "Onion seed", @""),
             new ItemSpawner("onion_seed:3", "i_onion_seed", "Onion seed", @""),
             new ItemSpawner("onion_crop:1", "i_onion_crop", "Onion", @"Effect on use: [c][3897FF]+(en)8[-][/c]"),
             new ItemSpawner("onion_crop:2", "i_onion_crop", "Onion", @"Effect on use: [c][3897FF]+(en)12[-][/c]"),
             new ItemSpawner("onion_crop:3", "i_onion_crop", "Onion", @"Effect on use: [c][3897FF]+(en)16[-][/c]"),
             new ItemSpawner("lentils_seed:1", "i_lentils_seed", "Lentil seed", @""),
             new ItemSpawner("lentils_seed:2", "i_lentils_seed", "Lentil seed", @""),
             new ItemSpawner("lentils_seed:3", "i_lentils_seed", "Lentil seed", @""),
             new ItemSpawner("lentils_crop:1", "i_lentils_crop", "Lentils", @"Effect on use: [c][3897FF]+(en)11[-][/c]"),
             new ItemSpawner("lentils_crop:2", "i_lentils_crop", "Lentils", @"Effect on use: [c][3897FF]+(en)16[-][/c]"),
             new ItemSpawner("lentils_crop:3", "i_lentils_crop", "Lentils", @"Effect on use: [c][3897FF]+(en)22[-][/c]"),
             new ItemSpawner("pumpkin_seed:1", "i_pumpkin_seed", "Pumpkin seed", @""),
             new ItemSpawner("pumpkin_seed:2", "i_pumpkin_seed", "Pumpkin seed", @""),
             new ItemSpawner("pumpkin_seed:3", "i_pumpkin_seed", "Pumpkin seed", @""),
             new ItemSpawner("pumpkin_crop:1", "i_pumpkin_crop", "Pumpkin", @"Effect on use: [c][3897FF]+(en)11[-][/c]"),
             new ItemSpawner("pumpkin_crop:2", "i_pumpkin_crop", "Pumpkin", @"Effect on use: [c][3897FF]+(en)16[-][/c]"),
             new ItemSpawner("pumpkin_crop:3", "i_pumpkin_crop", "Pumpkin", @"Effect on use: [c][3897FF]+(en)22[-][/c]"),
             new ItemSpawner("hop_seed:1", "i_hop_seed", "Hops seed", @""),
             new ItemSpawner("hop_seed:2", "i_hop_seed", "Hops seed", @""),
             new ItemSpawner("hop_seed:3", "i_hop_seed", "Hops seed", @""),
             new ItemSpawner("hop_crop:1", "i_hop_crop", "Hops", @""),
             new ItemSpawner("hop_crop:2", "i_hop_crop", "Hops", @""),
             new ItemSpawner("hop_crop:3", "i_hop_crop", "Hops", @""),
             new ItemSpawner("hamp_seed:1", "i_hamp_seed", "Hemp seed", @""),
             new ItemSpawner("hamp_seed:2", "i_hamp_seed", "Hemp seed", @""),
             new ItemSpawner("hamp_seed:3", "i_hamp_seed", "Hemp seed", @""),
             new ItemSpawner("hamp_crop:1", "i_hamp_crop", "Hemp", @""),
             new ItemSpawner("hamp_crop:2", "i_hamp_crop", "Hemp", @""),
             new ItemSpawner("hamp_crop:3", "i_hamp_crop", "Hemp", @""),
             new ItemSpawner("grapes_seed:1", "i_grapes_seed", "Grape seed", @""),
             new ItemSpawner("grapes_seed:2", "i_grapes_seed", "Grape seed", @""),
             new ItemSpawner("grapes_seed:3", "i_grapes_seed", "Grape seed", @""),
             new ItemSpawner("fruit:grapes_crop:1", "i_grapes_crop", "Grapes", @"Effect on use: [c][3897FF]+(en)20[-][/c]"),
             new ItemSpawner("fruit:grapes_crop:2", "i_grapes_crop", "Grapes", @"Effect on use: [c][3897FF]+(en)30[-][/c]"),
             new ItemSpawner("fruit:grapes_crop:3", "i_grapes_crop", "Grapes", @"Effect on use: [c][3897FF]+(en)35[-][/c]"),
             new ItemSpawner("pail_blood", "", "Bucket of blood", @""),
             new ItemSpawner("pail_wet_paper", "", "Paper glop", @""),
             new ItemSpawner("rope_hemp", "", "Hemp rope", @""),
             new ItemSpawner("sack_clear", "", "Fertilizer", @""),
             new ItemSpawner("energy_elixir", "i_flask_energy_elixir", "Energy elixir", @""),
             new ItemSpawner("sack_clock_gold", "", "Boost fertilizer II", @""),
             new ItemSpawner("sack_clock_silver", "", "Boost fertilizer I", @""),
             new ItemSpawner("growth_enhancer", "i_flask_growth_enhancer", "Growth enhancer", @""),
             new ItemSpawner("sack_star_silver", "", "Quality fertilizer I", @""),
             new ItemSpawner("flavor_enhancer", "i_flask_flavor_enhancer", "Flavor enhancer", @""),
             new ItemSpawner("sack_star_gold", "", "Quality fertilizer II", @""),
             new ItemSpawner("peat", "", "Peat", @""),
             new ItemSpawner("crop_waste", "", "Crop waste", @""),
             new ItemSpawner("seedling_bush_berry", "", "Bush berry seedling", @""),
             new ItemSpawner("seedling_tree_apple", "", "Tree apple seedling", @""),
             new ItemSpawner("shr_truffle", "", "Truffle", @""),
             new ItemSpawner("seed_oil", "", "Seed oil", @""),
             new ItemSpawner("box_vegetables_silver", "i_2h_box_vegetables_silver_star", "Box of vegetables", @""),
             new ItemSpawner("box_vegetables_gold", "i_2h_box_vegetables_gold_star", "Box of vegetables", @""),
             new ItemSpawner("box_goods", "i_2h_box_goods", "Box of goods", @""),
             new ItemSpawner("box_beer_1", "i_2h_box_beer_bronze", "Box of bronze beer", @""),
             new ItemSpawner("box_beer_2", "i_2h_box_beer_silver", "Box of silver beer", @""),
             new ItemSpawner("box_beer_3", "i_2h_box_beer_gold", "Box of gold beer", @""),
             new ItemSpawner("box_foodstuff_1", "i_2h_box_vegetable_bronze", "Box of foodstuffs 1", @""),
             new ItemSpawner("box_foodstuff_2", "i_2h_box_vegetable_silver", "Box of foodstuffs 2", @""),
             new ItemSpawner("box_foodstuff_3", "i_2h_box_vegetable_gold", "Box of foodstuffs 3", @""),
             new ItemSpawner("box_mead_1", "i_2h_box_beer_bronze", "Box of bronze mead", @""),
             new ItemSpawner("box_mead_2", "i_2h_box_beer_silver", "Box of silver mead", @""),
             new ItemSpawner("box_mead_3", "i_2h_box_beer_gold", "Box of gold mead", @""),
             new ItemSpawner("box_booz", "i_2h_box_booz", "Box of strong alcohol", @""),
             new ItemSpawner("box_wine_1", "i_2h_box_vine_bronze", "Box of bronze wine", @""),
             new ItemSpawner("box_wine_2", "i_2h_box_vine_silver", "Box of silver wine", @""),
             new ItemSpawner("box_wine_3", "i_2h_box_vine_gold", "Box of gold wine", @""),
             new ItemSpawner("foodstuff_1", "i_vegetables_1", "Foodstuffs 1", @"Effect on use: [c][3897FF]+(en)30[-][/c]"),
             new ItemSpawner("foodstuff_2", "i_vegetables_2", "Foodstuffs 2", @"Effect on use: [c][3897FF]+(en)60[-][/c]"),
             new ItemSpawner("foodstuff_3", "i_vegetables_2", "Foodstuffs 3", @"Effect on use: [c][3897FF]+(en)100[-][/c]"),
             new ItemSpawner("tavern_food_1", "i_ready_meal_1", "Tavern food 1", @"Effect on use: [c][3897FF]+(en)15[-][/c]"),
             new ItemSpawner("tavern_food_2", "i_ready_meal_2", "Tavern food 2", @"Effect on use: [c][3897FF]+(en)30[-][/c]"),
             new ItemSpawner("tavern_food_3", "i_ready_meal_3", "Tavern food 3", @"Effect on use: [c][3897FF]+(en)60[-][/c]"),
             new ItemSpawner("bat_wing", "", "Bat wing", @""),
             new ItemSpawner("jelly_slug", "", "Green jelly", @""),
             new ItemSpawner("jelly_slug_blue", "", "Blue jelly", @""),
             new ItemSpawner("jelly_slug_orange", "", "Orange jelly", @""),
             new ItemSpawner("jelly_slug_black", "", "Black jelly", @""),
             new ItemSpawner("bee", "", "Bee", @""),
             new ItemSpawner("skin_pig", "", "Pig skin", @""),
             new ItemSpawner("slime", "", "Slime", @""),
             new ItemSpawner("spider_web", "", "Spider web", @""),
             new ItemSpawner("ore_metal", "", "Iron ore", @"Can be extracted from iron veins in the mountains."),
             new ItemSpawner("detail_trash", "", "Metal scrap", @""),
             new ItemSpawner("1h_ore_metal", "", "Iron ore", @"Can be extracted from iron veins in the mountains."),
             new ItemSpawner("ingot_metal", "", "Iron ingot", @"A raw piece of iron, forged in the shape of an ingot."),
             new ItemSpawner("nails", "", "Nails", @""),
             new ItemSpawner("nails_bloody", "i_nails_rust_blood", "Bloody nails", @""),
             new ItemSpawner("detail_1", "", "Simple iron parts", @""),
             new ItemSpawner("detail_2", "", "Complex iron parts", @""),
             new ItemSpawner("whetstone", "", "Whetstone", @""),
             new ItemSpawner("2h_ore_silver", "", "Silver ore", @""),
             new ItemSpawner("powder_gold", "", "Gold powder", @""),
             new ItemSpawner("powder_silver", "", "Silver powder", @""),
             new ItemSpawner("powder_white", "", "White powder", @""),
             new ItemSpawner("powder_graphite", "", "Graphite powder", @""),
             new ItemSpawner("nugget_silver", "", "Silver nugget", @""),
             new ItemSpawner("nugget_gold", "", "Gold nugget", @""),
             new ItemSpawner("ingot_steel", "", "Steel ingot", @""),
             new ItemSpawner("ingot_silver", "", "Silver ingot", @""),
             new ItemSpawner("ingot_gold", "", "Gold ingot", @""),
             new ItemSpawner("detail_3", "", "Steel parts", @""),
             new ItemSpawner("pail_water", "", "Bucket of clear water", @"Use this item to get water."),
             new ItemSpawner("graphite", "", "Graphite", @""),
             new ItemSpawner("glass_0", "", "Glass", @""),
             new ItemSpawner("glass_1", "", "Conical flasks", @""),
             new ItemSpawner("glass_2", "", "Advanced conical flasks", @""),
             new ItemSpawner("sand_river", "", "River sand", @""),
             new ItemSpawner("chisel:chisel_1", "i_chisel_1", "Iron chisel", @""),
             new ItemSpawner("chisel:chisel_2:1", "i_chisel_2", "Steel chisel", @""),
             new ItemSpawner("chisel:chisel_2:2", "i_chisel_2", "Steel chisel", @""),
             new ItemSpawner("chisel:chisel_2:3", "i_chisel_2", "Steel chisel", @""),
             new ItemSpawner("jewelry_detail_gold", "", "Gold jewelry details", @""),
             new ItemSpawner("bijouterie_gold", "i_bijouterie_gold", "Jewelry", @""),
             new ItemSpawner("jewelry_detail_silver", "", "Silver jewelry details", @""),
             new ItemSpawner("lense", "", "Lens", @""),
             new ItemSpawner("axe_0", "", "Rusty axe", @"Energy consumption: [c][3897FF]-(en)1[-][/c]
             Tool efficiency: 70%"),
             new ItemSpawner("axe_1", "", "Axe I", @"Energy consumption: [c][3897FF]-(en)1[-][/c]
             Tool efficiency: 100%"),
             new ItemSpawner("axe_2", "", "Axe II", @"Energy consumption: [c][3897FF]-(en)1[-][/c]
             Tool efficiency: 150%"),
             new ItemSpawner("pickaxe_0", "", "Rusty pickaxe", @"Energy consumption: [c][3897FF]-(en)1[-][/c]
             Tool efficiency: 70%"),
             new ItemSpawner("pickaxe_1", "", "Pickaxe I", @"Energy consumption: [c][3897FF]-(en)1[-][/c]
             Tool efficiency: 100%"),
             new ItemSpawner("pickaxe_2", "", "Pickaxe II", @"Energy consumption: [c][3897FF]-(en)1[-][/c]
             Tool efficiency: 150%"),
             new ItemSpawner("ice_axe", "i_goc_iceaxe", "Ice axe", @"Energy consumption: [c][3897FF]-(en)1[-][/c]
             Tool efficiency: 200%
             This pickaxe is a quality tool, but you feel something's wrong with it. Maybe it's that little spot of dried blood that's on your mind?"),
             new ItemSpawner("shovel_0", "", "Rusty shovel", @"Energy consumption: [c][3897FF]-(en)1[-][/c]
             Tool efficiency: 70%"),
             new ItemSpawner("shovel_1", "", "Shovel I", @"Energy consumption: [c][3897FF]-(en)1[-][/c]
             Tool efficiency: 100%"),
             new ItemSpawner("shovel_2", "", "Shovel II", @"Energy consumption: [c][3897FF]-(en)1[-][/c]
             Tool efficiency: 150%"),
             new ItemSpawner("broken_sword", "", "Broken sword", @"Energy consumption: [c][3897FF]-(en)2[-][/c]
             5 damage"),
             new ItemSpawner("sword_0", "", "Rusty sword", @"Energy consumption: [c][3897FF]-(en)2[-][/c]
             5 damage"),
             new ItemSpawner("sword_1", "", "Sword", @"Energy consumption: [c][3897FF]-(en)1[-][/c]
             10 damage"),
             new ItemSpawner("sword_damask", "", "Damask sword", @"Energy consumption: [c][3897FF]-(en)1[-][/c]
             20 damage"),
             new ItemSpawner("sword_damask_gem", "", "Damask sword with gem", @"Energy consumption: [c][3897FF]-(en)1[-][/c]
             25 damage"),
             new ItemSpawner("sword_metal", "", "Metal sword", @"Energy consumption: [c][3897FF]-(en)2[-][/c]
             10 damage"),
             new ItemSpawner("sword_metal_gem", "", "Metal sword with gem", @"Energy consumption: [c][3897FF]-(en)2[-][/c]
             10 damage"),
             new ItemSpawner("sword_steel", "", "Steel sword", @"Energy consumption: [c][3897FF]-(en)2[-][/c]
             15 damage"),
             new ItemSpawner("sword_steel_gem", "", "Steel sword with gem", @"Energy consumption: [c][3897FF]-(en)2[-][/c]
             20 damage"),
             new ItemSpawner("hammer_0", "", "Rusty hammer", @"Energy consumption: [c][3897FF]-(en)1[-][/c]
             Tool efficiency: 70%"),
             new ItemSpawner("hammer_2", "", "Iron hammer", @"Energy consumption: [c][3897FF]-(en)1[-][/c]
             Tool efficiency: 100%"),
             new ItemSpawner("armor_lamellar_1", "", "Iron armor", @""),
             new ItemSpawner("armor_lamellar_2", "", "Steel armor", @""),
             new ItemSpawner("fishing_rod_0", "", "Simple fishing rod", @"Energy consumption: [c][3897FF]-(en)1[-][/c]
             Tool efficiency: 75%"),
             new ItemSpawner("fishing_rod_1", "", "Good fishing rod", @"Tool efficiency: 90%"),
             new ItemSpawner("fishing_rod_2", "", "Excellent fishing rod", @"Tool efficiency: 100%"),
             new ItemSpawner("fish_frog_green", "", "Frog", @""),
             new ItemSpawner("fish_gudgeon", "", "Gudgeon", @""),
             new ItemSpawner("fish_anchovy", "", "Anchovy", @""),
             new ItemSpawner("fish_tilapia", "", "Tilapia", @""),
             new ItemSpawner("fish_perch", "", "Perch", @""),
             new ItemSpawner("fish_eel", "i_fish_eel", "Eel", @""),
             new ItemSpawner("fish_bream:1", "i_fish_bream", "Bream", @""),
             new ItemSpawner("fish_bream:2", "i_fish_bream", "Bream", @""),
             new ItemSpawner("fish_sardine:1", "i_fish_sardine", "Sardine", @""),
             new ItemSpawner("fish_sardine:2", "i_fish_sardine", "Sardine", @""),
             new ItemSpawner("fish_tuna:1", "i_fish_tuna", "Tuna", @""),
             new ItemSpawner("fish_tuna:2", "i_fish_tuna", "Tuna", @""),
             new ItemSpawner("fish_pike:1", "i_fish_pike", "Pike", @""),
             new ItemSpawner("fish_pike:2", "i_fish_pike", "Pike", @""),
             new ItemSpawner("fish_crucian_silver:1", "i_fish_crucian_silver", "Silver crucian", @""),
             new ItemSpawner("fish_crucian_silver:2", "i_fish_crucian_silver", "Silver crucian", @""),
             new ItemSpawner("fish_salmon:2", "i_fish_salmon", "Salmon", @""),
             new ItemSpawner("fish_salmon:3", "i_fish_salmon", "Salmon", @""),
             new ItemSpawner("fish_sturgeon:2", "i_fish_sturgeon", "Sturgeon", @""),
             new ItemSpawner("fish_sturgeon:3", "i_fish_sturgeon", "Sturgeon", @""),
             new ItemSpawner("fish_carp", "", "Carp", @""),
             new ItemSpawner("fish_crucian_gold", "i_fish_crucian_gold", "Golden crucian", @""),
             new ItemSpawner("fish_goldfish", "i_fish_goldfish", "Goldfish", @""),
             new ItemSpawner("bait_gold", "", "Gold lure", @""),
             new ItemSpawner("bait_gem", "", "Lure with a gem", @""),
             new ItemSpawner("bait_steel", "", "Steel lure", @""),
             new ItemSpawner("wood", "", "Log", @""),
             new ItemSpawner("wood1", "", "Wood billet", @""),
             new ItemSpawner("flitch", "", "Flitch", @""),
             new ItemSpawner("stick", "", "Wooden stick", @"Perfect for poking people and starting fires."),
             new ItemSpawner("wooden_plank", "", "Wooden plank", @""),
             new ItemSpawner("firewood", "", "Firewood", @""),
             new ItemSpawner("spike_1", "", "Wood wedge", @""),
             new ItemSpawner("wood_balk_1", "", "Wooden beam", @""),
             new ItemSpawner("carved_wood:1", "i_carved_wood", "Carved wood", @""),
             new ItemSpawner("carved_wood:2", "i_carved_wood", "Carved wood", @""),
             new ItemSpawner("carved_wood:3", "i_carved_wood", "Carved wood", @""),
             new ItemSpawner("wchips", "", "Wood chips", @""),
             new ItemSpawner("wood_constr_1", "", "Jointing", @""),
             new ItemSpawner("wood_magic_1", "", "Magic wood plank", @""),
             new ItemSpawner("owl_wood", "", "Wooden owl", @""),
             new ItemSpawner("repair_wdn", "i_repair_wd", "Wood repair kit", @""),
             new ItemSpawner("stone", "", "Stone", @""),
             new ItemSpawner("1h_stone", "", "", @""),
             new ItemSpawner("stone_plate_1", "", "A piece of stone", @""),
             new ItemSpawner("stone_plate_2", "", "A polished brick of stone", @""),
             new ItemSpawner("stone_plate_3", "", "A carved piece of stone", @""),
             new ItemSpawner("water", "", "Water", @""),
             new ItemSpawner("sulfur", "", "Sulfur", @""),
             new ItemSpawner("clay", "", "Clay", @""),
             new ItemSpawner("coal", "", "Coal", @""),
             new ItemSpawner("pyrite", "", "Pyrite", @""),
             new ItemSpawner("lifestone", "", "Limestone", @""),
             new ItemSpawner("marble", "", "Marble", @""),
             new ItemSpawner("1h_marble", "", "", @""),
             new ItemSpawner("marble_plate_1", "", "A piece of marble", @""),
             new ItemSpawner("marble_plate_2", "", "A polished brick of marble", @""),
             new ItemSpawner("marble_plate_3:1", "i_bust_marble", "A carved piece of marble", @""),
             new ItemSpawner("marble_plate_3:2", "i_bust_marble", "A carved piece of marble", @""),
             new ItemSpawner("marble_plate_3:3", "i_bust_marble", "A carved piece of marble", @""),
             new ItemSpawner("marble_gold", "", "Spirit stone", @""),
             new ItemSpawner("1h_marble_gold", "", "", @""),
             new ItemSpawner("marble_gold_plate_1", "", "A piece of Spirit stone", @""),
             new ItemSpawner("marble_gold_plate_2", "", "A polished brick of Spirit stone", @""),
             new ItemSpawner("marble_gold_plate_3", "", "Stone", @""),
             new ItemSpawner("obsidian", "", "Silence stone", @""),
             new ItemSpawner("1h_obsidian", "", "Obsidian", @"A mysterious stone. It's worth examining."),
             new ItemSpawner("obsidian_plate_1", "", "A piece of Silence stone", @""),
             new ItemSpawner("obsidian_plate_2", "", "A polished brick of Silence stone", @""),
             new ItemSpawner("obsidian_plate_3", "", "A carved piece of Silence stone", @""),
             new ItemSpawner("ceramic_1", "", "Ceramic bowls", @""),
             new ItemSpawner("ceramic_2", "", "Ceramic jug", @""),
             new ItemSpawner("ceramic_3", "", "Porcelain pitcher", @""),
             new ItemSpawner("funeral_urn_1", "i_funeral_urn_1", "Ceramic funeral urn", @""),
             new ItemSpawner("funeral_urn_2", "i_funeral_urn_2", "Porcelain funeral urn", @""),
             new ItemSpawner("jug_empty", "", "Empty jug", @""),
             new ItemSpawner("bust_marble", "", "Marble bust", @""),
             new ItemSpawner("spike_2", "", "Iron wedge", @""),
             new ItemSpawner("faceted_diamond", "", "Faceted diamond", @""),
             new ItemSpawner("faceted_emerald", "", "Faceted emerald", @""),
             new ItemSpawner("repair_stn", "", "Stone repair kit", @""),
             new ItemSpawner("repair_mrb", "", "Marble repair kit", @""),
             new ItemSpawner("polishing_paste", "", "Polishing paste", @""),
             new ItemSpawner("packet_meat", "", "Package of meat", @""),
             new ItemSpawner("raw_meat_sliced", "", "Raw sliced meat", @""),
             new ItemSpawner("fillet_fish_white", "i_fillet_fish_white", "White fish fillet", @""),
             new ItemSpawner("fillet_fish:fillet_fish_red:1", "i_fillet_fish_red", "Quality fish fillet", @""),
             new ItemSpawner("fillet_fish:fillet_fish_red:2", "i_fillet_fish_red", "Quality fish fillet", @""),
             new ItemSpawner("fillet_fish:fillet_fish_red:3", "i_fillet_fish_red", "Quality fish fillet", @""),
             new ItemSpawner("fillet_fish:fillet_fish_blue:1", "i_fillet_fish_blue", "Blue fish fillet", @""),
             new ItemSpawner("fillet_fish:fillet_fish_blue:2", "i_fillet_fish_blue", "Blue fish fillet", @""),
             new ItemSpawner("fillet_fish:fillet_fish_blue:3", "i_fillet_fish_blue", "Blue fish fillet", @""),
             new ItemSpawner("egg_chicken", "", "Chicken egg", @""),
             new ItemSpawner("taste_booster:salt", "i_salt", "Salt", @""),
             new ItemSpawner("dough", "i_dough_1", "Dough", @""),
             new ItemSpawner("dough_2", "", "Pastry dough", @""),
             new ItemSpawner("potion_berries_juice", "", "Berry juice", @""),
             new ItemSpawner("jug_milk", "", "Jug of milk", @""),
             new ItemSpawner("butter", "", "Butter", @""),
             new ItemSpawner("cheese", "", "Cheese", @""),
             new ItemSpawner("snack:fried_egg", "i_fried_egg", "Fried egg", @"Effect on use: [c][3897FF]+(en)13[-][/c]"),
             new ItemSpawner("snack:bread", "i_bread", "Bread", @"Effect on use: [c][3897FF]+(en)15[-][/c]"),
             new ItemSpawner("snack:onion_ring:1", "i_onion_ring", "Onion rings", @"Effect on use: [c][3897FF]+(en)12[-][/c], [c][C16000]Beer thirst[-][/c] (Beer tastes much better now!)"),
             new ItemSpawner("snack:onion_ring:2", "i_onion_ring", "Onion rings", @"Effect on use: [c][3897FF]+(en)19[-][/c], [c][C16000]Beer thirst[-][/c] (Beer tastes much better now!)"),
             new ItemSpawner("snack:onion_ring:3", "i_onion_ring", "Onion rings", @"Effect on use: [c][3897FF]+(en)24[-][/c], [c][C16000]Beer thirst[-][/c] (Beer tastes much better now!)"),
             new ItemSpawner("snack:baked_apple", "i_baked_apple", "Baked apple", @"Effect on use: [c][3897FF]+(en)8[-][/c]"),
             new ItemSpawner("snack:bowl_sauerkraut", "i_bowl_sauerkraut", "A bowl of sauerkraut", @"Effect on use: [c][3897FF]+(en)30[-][/c], [c][C16000]Slow metabolism[-][/c] (All buffs last longer.)"),
             new ItemSpawner("snack:baked_kebab_7", "i_baked_kebab_7", "Baked mushrooms", @"Effect on use: [c][3897FF]+(en)12[-][/c]"),
             new ItemSpawner("snack:pancakes", "i_pancakes", "Pancakes", @"Effect on use: [c][3897FF]+(en)40[-][/c]"),
             new ItemSpawner("snack:sandwich", "i_sandwich", "Sandwich", @"Effect on use: [c][3897FF]+(en)20[-][/c]"),
             new ItemSpawner("snack:toasts:1", "i_toasts", "Toasts with onions", @"Effect on use: [c][3897FF]+(en)13[-][/c], [c][C16000]Beer thirst[-][/c] (Beer tastes much better now!)"),
             new ItemSpawner("snack:toasts:2", "i_toasts", "Toasts with onions", @"Effect on use: [c][3897FF]+(en)19[-][/c], [c][C16000]Beer thirst[-][/c] (Beer tastes much better now!)"),
             new ItemSpawner("snack:toasts:3", "i_toasts", "Toasts with onions", @"Effect on use: [c][3897FF]+(en)24[-][/c], [c][C16000]Beer thirst[-][/c] (Beer tastes much better now!)"),
             new ItemSpawner("meal:omlette", "i_omlette", "Omelette", @"Effect on use: [c][3897FF]+(en)24[-][/c]"),
             new ItemSpawner("meal:nuggets_fish", "i_nuggets_fish", "Fish nuggets", @"Effect on use: [c][3897FF]+(en)30[-][/c], [c][C16000]Fast reflexes[-][/c] (You have additional time to hook a fish.)"),
             new ItemSpawner("meal:cutlet_carrot", "i_cutlet_carrot", "Carrot cutlet", @"Effect on use: [c][3897FF]+(en)15[-][/c]"),
             new ItemSpawner("meal:bowl_lentil:1", "i_bowl_lentil", "A bowl of lentils", @"Effect on use: [c][3897FF]+(en)25[-][/c], [c][C16000]Deep sleep[-][/c] (Energy regeneration during sleeping is increased.)"),
             new ItemSpawner("meal:bowl_lentil:2", "i_bowl_lentil", "A bowl of lentils", @"Effect on use: [c][3897FF]+(en)30[-][/c], [c][C16000]Deep sleep[-][/c] (Energy regeneration during sleeping is increased.)"),
             new ItemSpawner("meal:bowl_lentil:3", "i_bowl_lentil", "A bowl of lentils", @"Effect on use: [c][3897FF]+(en)36[-][/c], [c][C16000]Deep sleep[-][/c] (Energy regeneration during sleeping is increased.)"),
             new ItemSpawner("meal:bowl_pumpkin:1", "i_bowl_pumpkin", "A bowl of pumpkin soup", @"Effect on use: [c][3897FF]+(en)24[-][/c], [c][C16000]Deep sleep[-][/c] (Energy regeneration during sleeping is increased.)"),
             new ItemSpawner("meal:bowl_pumpkin:2", "i_bowl_pumpkin", "A bowl of pumpkin soup", @"Effect on use: [c][3897FF]+(en)30[-][/c], [c][C16000]Deep sleep[-][/c] (Energy regeneration during sleeping is increased.)"),
             new ItemSpawner("meal:bowl_pumpkin:3", "i_bowl_pumpkin", "A bowl of pumpkin soup", @"Effect on use: [c][3897FF]+(en)36[-][/c], [c][C16000]Deep sleep[-][/c] (Energy regeneration during sleeping is increased.)"),
             new ItemSpawner("meal:baked_fish", "i_baked_fish", "Baked fish", @"Effect on use: [c][3897FF]+(en)18[-][/c], [c][C16000]Good fisherman[-][/c] (You don't let fish off the hook easily.)"),
             new ItemSpawner("meal:baked_salmon:1", "i_baked_salmon", "Baked salmon", @"Effect on use: [c][3897FF]+(en)36[-][/c]"),
             new ItemSpawner("meal:baked_salmon:2", "i_baked_salmon", "Baked salmon", @"Effect on use: [c][3897FF]+(en)48[-][/c]"),
             new ItemSpawner("meal:baked_salmon:3", "i_baked_salmon", "Baked salmon", @"Effect on use: [c][3897FF]+(en)70[-][/c]"),
             new ItemSpawner("meal:honey_fish:1", "i_baked_fish_blue", "Royal fish", @"Effect on use: [c][3897FF]+(en)48[-][/c]"),
             new ItemSpawner("meal:honey_fish:2", "i_baked_fish_blue", "Royal fish", @"Effect on use: [c][3897FF]+(en)60[-][/c]"),
             new ItemSpawner("meal:honey_fish:3", "i_baked_fish_blue", "Royal fish", @"Effect on use: [c][3897FF]+(en)84[-][/c]"),
             new ItemSpawner("meal:soup_fish", "i_soup_fish", "Fish soup", @"Effect on use: [c][3897FF]+(en)24[-][/c], [c][C16000]Good fisherman[-][/c] (You don't let fish off the hook easily.)"),
             new ItemSpawner("meal:baked_kebab_1:1", "i_baked_kebab_1", "Baked kebab", @"Effect on use: [c][3897FF]+(en)30[-][/c], [c][C16000]Tough mood[-][/c] (Incoming damage is reduced.)
             Kebab with fish and pumpkin"),
             new ItemSpawner("meal:baked_kebab_1:2", "i_baked_kebab_1", "Baked kebab", @"Effect on use: [c][3897FF]+(en)42[-][/c], [c][C16000]Tough mood[-][/c] (Incoming damage is reduced.)
             Kebab with fish and pumpkin"),
             new ItemSpawner("meal:baked_kebab_1:3", "i_baked_kebab_1", "Baked kebab", @"Effect on use: [c][3897FF]+(en)60[-][/c], [c][C16000]Tough mood[-][/c] (Incoming damage is reduced.)
             Kebab with fish and pumpkin"),
             new ItemSpawner("meal:baked_kebab_2:1", "i_baked_kebab_2", "Baked kebab", @"Effect on use: [c][3897FF]+(en)30[-][/c], [c][C16000]Rage[-][/c] (You deal additional damage to monsters.)
             Kebab with fish and onion"),
             new ItemSpawner("meal:baked_kebab_2:2", "i_baked_kebab_2", "Baked kebab", @"Effect on use: [c][3897FF]+(en)42[-][/c], [c][C16000]Rage[-][/c] (You deal additional damage to monsters.)
             Kebab with fish and onion"),
             new ItemSpawner("meal:baked_kebab_2:3", "i_baked_kebab_2", "Baked kebab", @"Effect on use: [c][3897FF]+(en)53[-][/c], [c][C16000]Rage[-][/c] (You deal additional damage to monsters.)
             Kebab with fish and onion"),
             new ItemSpawner("meal:baked_kebab_5:1", "i_baked_kebab_5", "Baked kebab", @"Effect on use: [c][3897FF]+(en)24[-][/c], [c][C16000]Tough mood[-][/c] (Incoming damage is reduced.)
             Kebab with fish and mushrooms"),
             new ItemSpawner("meal:baked_kebab_5:2", "i_baked_kebab_5", "Baked kebab", @"Effect on use: [c][3897FF]+(en)30[-][/c], [c][C16000]Tough mood[-][/c] (Incoming damage is reduced.)
             Kebab with fish and mushrooms"),
             new ItemSpawner("meal:baked_kebab_5:3", "i_baked_kebab_5", "Baked kebab", @"Effect on use: [c][3897FF]+(en)42[-][/c], [c][C16000]Tough mood[-][/c] (Incoming damage is reduced.)
             Kebab with fish and mushrooms"),
             new ItemSpawner("meal:baked_meat", "i_baked_meat", "Baked meat", @"Effect on use: [c][3897FF]+(en)18[-][/c]"),
             new ItemSpawner("meal:baked_pumpkin:1", "i_baked_pumpkin", "Baked pumpkin", @"Effect on use: [c][3897FF]+(en)18[-][/c], [c][C16000]Slow metabolism[-][/c] (All buffs last longer.)"),
             new ItemSpawner("meal:baked_pumpkin:2", "i_baked_pumpkin", "Baked pumpkin", @"Effect on use: [c][3897FF]+(en)24[-][/c], [c][C16000]Slow metabolism[-][/c] (All buffs last longer.)"),
             new ItemSpawner("meal:baked_pumpkin:3", "i_baked_pumpkin", "Baked pumpkin", @"Effect on use: [c][3897FF]+(en)30[-][/c], [c][C16000]Slow metabolism[-][/c] (All buffs last longer.)"),
             new ItemSpawner("meal:burger:1", "i_burger", "Burger", @"Effect on use: [c][3897FF]+(en)36[-][/c], [c][C16000]Steady hand[-][/c] (A steady hand reduces the chances of making a surgical error.)"),
             new ItemSpawner("meal:burger:2", "i_burger", "Burger", @"Effect on use: [c][3897FF]+(en)42[-][/c], [c][C16000]Steady hand[-][/c] (A steady hand reduces the chances of making a surgical error.)"),
             new ItemSpawner("meal:burger:3", "i_burger", "Burger", @"Effect on use: [c][3897FF]+(en)48[-][/c], [c][C16000]Steady hand[-][/c] (A steady hand reduces the chances of making a surgical error.)"),
             new ItemSpawner("meal:lasagne:1", "i_lasagne", "Lasagna", @"Effect on use: [c][3897FF]+(en)30[-][/c], [c][C16000]Hard worker[-][/c] (You spend less energy working with axes and pickaxes.)"),
             new ItemSpawner("meal:lasagne:2", "i_lasagne", "Lasagna", @"Effect on use: [c][3897FF]+(en)36[-][/c], [c][C16000]Hard worker[-][/c] (You spend less energy working with axes and pickaxes.)"),
             new ItemSpawner("meal:lasagne:3", "i_lasagne", "Lasagna", @"Effect on use: [c][3897FF]+(en)40[-][/c], [c][C16000]Hard worker[-][/c] (You spend less energy working with axes and pickaxes.)"),
             new ItemSpawner("meal:pasta", "i_pasta", "Pasta", @"Effect on use: [c][3897FF]+(en)60[-][/c], [c][C16000]Hard worker[-][/c] (You spend less energy working with axes and pickaxes.)"),
             new ItemSpawner("meal:soup_red_green:1", "i_soup_red_green", "Cabbage soup", @"Effect on use: [c][3897FF]+(en)36[-][/c], [c][C16000]Deep sleep[-][/c] (Energy regeneration during sleeping is increased.)"),
             new ItemSpawner("meal:soup_red_green:2", "i_soup_red_green", "Cabbage soup", @"Effect on use: [c][3897FF]+(en)42[-][/c], [c][C16000]Deep sleep[-][/c] (Energy regeneration during sleeping is increased.)"),
             new ItemSpawner("meal:soup_red_green:3", "i_soup_red_green", "Cabbage soup", @"Effect on use: [c][3897FF]+(en)48[-][/c], [c][C16000]Deep sleep[-][/c] (Energy regeneration during sleeping is increased.)"),
             new ItemSpawner("meal:soup_red_yellow:1", "i_soup_red_yellow", "Pumpkin soup", @"Effect on use: [c][3897FF]+(en)48[-][/c], [c][C16000]Deep sleep[-][/c] (Energy regeneration during sleeping is increased.)"),
             new ItemSpawner("meal:soup_red_yellow:2", "i_soup_red_yellow", "Pumpkin soup", @"Effect on use: [c][3897FF]+(en)60[-][/c], [c][C16000]Deep sleep[-][/c] (Energy regeneration during sleeping is increased.)"),
             new ItemSpawner("meal:soup_red_yellow:3", "i_soup_red_yellow", "Pumpkin soup", @"Effect on use: [c][3897FF]+(en)72[-][/c], [c][C16000]Deep sleep[-][/c] (Energy regeneration during sleeping is increased.)"),
             new ItemSpawner("meal:soup_yellow_green:1", "i_soup_yellow_green", "Vegetable soup", @"Effect on use: [c][3897FF]+(en)42[-][/c], [c][C16000]Deep sleep[-][/c] (Energy regeneration during sleeping is increased.)"),
             new ItemSpawner("meal:soup_yellow_green:2", "i_soup_yellow_green", "Vegetable soup", @"Effect on use: [c][3897FF]+(en)54[-][/c], [c][C16000]Deep sleep[-][/c] (Energy regeneration during sleeping is increased.)"),
             new ItemSpawner("meal:soup_yellow_green:3", "i_soup_yellow_green", "Vegetable soup", @"Effect on use: [c][3897FF]+(en)66[-][/c], [c][C16000]Deep sleep[-][/c] (Energy regeneration during sleeping is increased.)"),
             new ItemSpawner("meal:beet_slice", "i_beet_cuts", "Beet slices", @"Effect on use: [c][3897FF]+(en)18[-][/c]"),
             new ItemSpawner("dessert:jelly_green", "i_jelly_green", "Green jelly", @"Effect on use: [c][3897FF]+(en)30[-][/c]"),
             new ItemSpawner("dessert:jelly_red", "i_jelly_red", "Red jelly", @"Effect on use: [c][3897FF]+(en)36[-][/c]"),
             new ItemSpawner("dessert:muffin", "i_muffin", "Muffin", @"Effect on use: [c][3897FF]+(en)24[-][/c]"),
             new ItemSpawner("dessert:croissant", "i_croissant", "Croissant", @"Effect on use: [c][3897FF]+(en)30[-][/c]"),
             new ItemSpawner("dessert:pie", "i_pie", "Cake", @"Effect on use: [c][3897FF]+(en)95[-][/c], [c][C16000]Circumspect[-][/c] (You get extra points when studying new items.)"),
             new ItemSpawner("dessert:pie_1", "i_pie_1", "Berry pie", @"Effect on use: [c][3897FF]+(en)35[-][/c]"),
             new ItemSpawner("dessert:pie_2:1", "i_pie_2", "Grape pie", @"Effect on use: [c][3897FF]+(en)80[-][/c], [c][C16000]Circumspect[-][/c] (You get extra points when studying new items.)"),
             new ItemSpawner("dessert:pie_2:2", "i_pie_2", "Grape pie", @"Effect on use: [c][3897FF]+(en)100[-][/c], [c][C16000]Circumspect[-][/c] (You get extra points when studying new items.)"),
             new ItemSpawner("dessert:pie_2:3", "i_pie_2", "Grape pie", @"Effect on use: [c][3897FF]+(en)100[-][/c], [c][C16000]Circumspect[-][/c] (You get extra points when studying new items.)"),
             new ItemSpawner("dinner:1", "i_silver_platter", "Dinner", @""),
             new ItemSpawner("dinner:2", "i_silver_platter", "Dinner", @""),
             new ItemSpawner("dinner:3", "i_silver_platter", "Dinner", @""),
             new ItemSpawner("baked_kebab_3", "", "Baked kebab 3", @""),
             new ItemSpawner("baked_kebab_4", "", "Baked kebab 4", @""),
             new ItemSpawner("baked_kebab_6", "", "Baked kebab 6", @""),
             new ItemSpawner("snack:grated_carrot", "i_grated_carrot", "Grated carrot", @"Effect on use: [c][3897FF]+(en)20[-][/c]"),
             new ItemSpawner("snack:grated_beetroot", "i_grated_beetroot", "Grated beets", @"Effect on use: [c][3897FF]+(en)30[-][/c]"),
             new ItemSpawner("snack:boiled_egg", "i_boiled_egg", "Boiled egg", @"Effect on use: [c][3897FF]+(en)20[-][/c]"),
             new ItemSpawner("snack:vegetable_salad:1", "i_vegetable_salad", "Vegetable salad", @"Effect on use: [c][3897FF]+(en)12[-][/c], [c][C16000]Deep sleep[-][/c] (Energy regeneration during sleeping is increased.)"),
             new ItemSpawner("snack:vegetable_salad:2", "i_vegetable_salad", "Vegetable salad", @"Effect on use: [c][3897FF]+(en)14[-][/c], [c][C16000]Deep sleep[-][/c] (Energy regeneration during sleeping is increased.)"),
             new ItemSpawner("snack:vegetable_salad:3", "i_vegetable_salad", "Vegetable salad", @"Effect on use: [c][3897FF]+(en)16[-][/c], [c][C16000]Deep sleep[-][/c] (Energy regeneration during sleeping is increased.)"),
             new ItemSpawner("meal:cheese_pie", "i_cheese_pie", "Cheese pie", @"Effect on use: [c][3897FF]+(en)35[-][/c], [c][C16000]Handyman mood[-][/c] (You have a better chance to craft something of good quality.)"),
             new ItemSpawner("meal:creamy_vegetable_soup:1", "i_creamy_vegetable_soup", "Creamy vegetable soup", @"Effect on use: [c][3897FF]+(en)15[-][/c], [c][C16000]Slow metabolism[-][/c] (All buffs last longer.)"),
             new ItemSpawner("meal:creamy_vegetable_soup:2", "i_creamy_vegetable_soup", "Creamy vegetable soup", @"Effect on use: [c][3897FF]+(en)20[-][/c], [c][C16000]Slow metabolism[-][/c] (All buffs last longer.)"),
             new ItemSpawner("meal:creamy_vegetable_soup:3", "i_creamy_vegetable_soup", "Creamy vegetable soup", @"Effect on use: [c][3897FF]+(en)25[-][/c], [c][C16000]Slow metabolism[-][/c] (All buffs last longer.)"),
             new ItemSpawner("meal:lentil_porridge:1", "i_lentil_porridge", "Lentil porridge", @"Effect on use: [c][3897FF]+(en)14[-][/c]"),
             new ItemSpawner("meal:lentil_porridge:2", "i_lentil_porridge", "Lentil porridge", @"Effect on use: [c][3897FF]+(en)18[-][/c]"),
             new ItemSpawner("meal:lentil_porridge:3", "i_lentil_porridge", "Lentil porridge", @"Effect on use: [c][3897FF]+(en)22[-][/c]"),
             new ItemSpawner("meal:greek_lentil_soup:1", "i_greek_lentil_soup", "Fancy lentil soup", @"Effect on use: [c][3897FF]+(en)20[-][/c], [c][C16000]Circumspect[-][/c] (You get extra points when studying new items.)"),
             new ItemSpawner("meal:greek_lentil_soup:2", "i_greek_lentil_soup", "Fancy lentil soup", @"Effect on use: [c][3897FF]+(en)28[-][/c], [c][C16000]Circumspect[-][/c] (You get extra points when studying new items.)"),
             new ItemSpawner("meal:greek_lentil_soup:3", "i_greek_lentil_soup", "Fancy lentil soup", @"Effect on use: [c][3897FF]+(en)36[-][/c], [c][C16000]Circumspect[-][/c] (You get extra points when studying new items.)"),
             new ItemSpawner("meal:vegetable_patty:1", "i_vegetable_patty", "Vegetable patty", @"Effect on use: [c][3897FF]+(en)12[-][/c], [c][C16000]Hard worker[-][/c] (You spend less energy working with axes and pickaxes.)"),
             new ItemSpawner("meal:vegetable_patty:2", "i_vegetable_patty", "Vegetable patty", @"Effect on use: [c][3897FF]+(en)15[-][/c], [c][C16000]Hard worker[-][/c] (You spend less energy working with axes and pickaxes.)"),
             new ItemSpawner("meal:vegetable_patty:3", "i_vegetable_patty", "Vegetable patty", @"Effect on use: [c][3897FF]+(en)18[-][/c], [c][C16000]Hard worker[-][/c] (You spend less energy working with axes and pickaxes.)"),
             new ItemSpawner("meal:mushroom_patty", "i_mushroom_patty", "Mushroom patty", @"Effect on use: [c][3897FF]+(en)8[-][/c], [c][C16000]Hard worker[-][/c] (You spend less energy working with axes and pickaxes.)"),
             new ItemSpawner("meal:сheese_patty", "i_сheese_patty", "Cheese patty", @"Effect on use: [c][3897FF]+(en)16[-][/c], [c][C16000]Hard worker[-][/c] (You spend less energy working with axes and pickaxes.)"),
             new ItemSpawner("meal:vegetable_stew:1", "i_vegetable_stew", "Vegetable stew", @"Effect on use: [c][3897FF]+(en)20[-][/c], [c][C16000]Rage[-][/c] (You deal additional damage to monsters.)"),
             new ItemSpawner("meal:vegetable_stew:2", "i_vegetable_stew", "Vegetable stew", @"Effect on use: [c][3897FF]+(en)24[-][/c], [c][C16000]Rage[-][/c] (You deal additional damage to monsters.)"),
             new ItemSpawner("meal:vegetable_stew:3", "i_vegetable_stew", "Vegetable stew", @"Effect on use: [c][3897FF]+(en)28[-][/c], [c][C16000]Rage[-][/c] (You deal additional damage to monsters.)"),
             new ItemSpawner("meal:cream_of_mushroom_soup", "i_cream_of_mushroom_soup", "Cream of mushroom soup", @"Effect on use: [c][3897FF]+(en)13[-][/c], [c][C16000]Tough mood[-][/c] (Incoming damage is reduced.)"),
             new ItemSpawner("meal:lentil_cutlets:1", "i_lentil_cutlets", "Lentil cutlets", @"Effect on use: [c][3897FF]+(en)12[-][/c], [c][C16000]Circumspect[-][/c] (You get extra points when studying new items.)"),
             new ItemSpawner("meal:lentil_cutlets:2", "i_lentil_cutlets", "Lentil cutlets", @"Effect on use: [c][3897FF]+(en)16[-][/c], [c][C16000]Circumspect[-][/c] (You get extra points when studying new items.)"),
             new ItemSpawner("meal:lentil_cutlets:3", "i_lentil_cutlets", "Lentil cutlets", @"Effect on use: [c][3897FF]+(en)20[-][/c], [c][C16000]Circumspect[-][/c] (You get extra points when studying new items.)"),
             new ItemSpawner("dessert:cheesecake", "i_cheesecake", "Cheesecake", @"Effect on use: [c][3897FF]+(en)35[-][/c], [c][C16000]Circumspect[-][/c] (You get extra points when studying new items.)"),
             new ItemSpawner("dessert:panna_cotta", "i_panna_cotta", "Panna cotta", @"Effect on use: [c][3897FF]+(en)13[-][/c], [c][C16000]Steady hand[-][/c] (A steady hand reduces the chances of making a surgical error.)"),
             new ItemSpawner("dessert:honey_pudding", "i_honey_pudding", "Honey pudding", @"Effect on use: [c][3897FF]+(en)55[-][/c], [c][C16000]Steady hand[-][/c] (A steady hand reduces the chances of making a surgical error.)"),
             new ItemSpawner("dessert:berry_pudding", "i_berry_pudding", "Berry pudding", @"Effect on use: [c][3897FF]+(en)48[-][/c], [c][C16000]Steady hand[-][/c] (A steady hand reduces the chances of making a surgical error.)"),
             new ItemSpawner("dessert:honey_cake", "i_honey_cake", "Honey cake", @"Effect on use: [c][3897FF]+(en)55[-][/c], [c][C16000]Circumspect[-][/c] (You get extra points when studying new items.)"),
             new ItemSpawner("recipe_simple_snacks", "i_recipe_simple_snacks", "Recipe: Simple snacks", @""),
             new ItemSpawner("recipe_vegetable_set", "i_recipe_vegetable_set", "Recipe: Vegetable set", @""),
             new ItemSpawner("recipe_milk_processing", "i_recipe_milk_processing", "Recipe: Milk processing", @""),
             new ItemSpawner("recipe_in_lentil_we_trust", "i_recipe_in_lentil_we_trust", "Recipe: In Lentil We Trust", @""),
             new ItemSpawner("recipe_patties", "i_recipe_patties", "Recipe: Patties", @""),
             new ItemSpawner("recipe_cheese_dishes", "i_recipe_cheese_dishes", "Recipe: Cheese dishes", @""),
             new ItemSpawner("recipe_jelly_desserts", "i_recipe_jelly_desserts", "Recipe: Jelly desserts", @""),
             new ItemSpawner("pail_apple_juice", "i_pail_dirty_water_1", "Pail of apple juice", @""),
             new ItemSpawner("bottle_apple_juice", "i_bottle_apple_vine_1", "Bottle of apple juice", @"Effect on use: [c][3897FF]+(en)12[-][/c]"),
             new ItemSpawner("bottle_apple_braga", "i_bottle_apple_vine_2", "Bottle of apple ferment", @"Effect on use: [c][3897FF]+(en)22[-][/c]"),
             new ItemSpawner("pail_berry_juice", "i_pail_juce_violet", "Pail of berry juice", @""),
             new ItemSpawner("bottle_berry_juice", "i_bottle_berry_vine_1", "Bottle of berry juice", @"Effect on use: [c][3897FF]+(en)18[-][/c]"),
             new ItemSpawner("bottle_berry_braga", "i_bottle_berry_vine_2", "Bottle of berry ferment", @"Effect on use: [c][3897FF]+(en)34[-][/c]"),
             new ItemSpawner("pail_grape_juice:1", "i_pail_juce_violet_d", "Pail of grape juice", @""),
             new ItemSpawner("pail_grape_juice:2", "i_pail_juce_violet_d", "Pail of grape juice", @""),
             new ItemSpawner("pail_grape_juice:3", "i_pail_juce_violet_d", "Pail of grape juice", @""),
             new ItemSpawner("bottle_grape_juice:1", "i_bottle_red_vine_1", "Bottle of grape juice", @"Effect on use: [c][F4203F]+(hp)10[-][/c] [c][3897FF]+(en)36[-][/c]"),
             new ItemSpawner("bottle_grape_juice:2", "i_bottle_red_vine_1", "Bottle of grape juice", @"Effect on use: [c][F4203F]+(hp)15[-][/c] [c][3897FF]+(en)48[-][/c]"),
             new ItemSpawner("bottle_grape_juice:3", "i_bottle_red_vine_1", "Bottle of grape juice", @"Effect on use: [c][F4203F]+(hp)20[-][/c] [c][3897FF]+(en)60[-][/c]"),
             new ItemSpawner("bottle_red_vine:1", "i_bottle_red_vine_2", "Red wine", @"Effect on use: [c][F4203F]+(hp)30[-][/c] [c][3897FF]+(en)85[-][/c]"),
             new ItemSpawner("bottle_red_vine:2", "i_bottle_red_vine_2", "Red wine", @"Effect on use: [c][F4203F]+(hp)30[-][/c] [c][3897FF]+(en)102[-][/c]"),
             new ItemSpawner("bottle_red_vine:3", "i_bottle_red_vine_2", "Red wine", @"Effect on use: [c][F4203F]+(hp)30[-][/c] [c][3897FF]+(en)114[-][/c]"),
             new ItemSpawner("pail_beer:1", "", "Wort", @""),
             new ItemSpawner("pail_beer:2", "", "Wort", @""),
             new ItemSpawner("pail_beer:3", "", "Wort", @""),
             new ItemSpawner("cup_beer:1", "i_cup_beer", "A mug of beer", @"Effect on use: [c][F4203F]+(hp)5[-][/c] [c][3897FF]+(en)26[-][/c]"),
             new ItemSpawner("cup_beer:2", "i_cup_beer", "A mug of beer", @"Effect on use: [c][F4203F]+(hp)5[-][/c] [c][3897FF]+(en)29[-][/c]"),
             new ItemSpawner("cup_beer:3", "i_cup_beer", "A mug of beer", @"Effect on use: [c][F4203F]+(hp)10[-][/c] [c][3897FF]+(en)35[-][/c]"),
             new ItemSpawner("cup_mead:1", "i_cup_mead", "A mug of mead", @"Effect on use: [c][F4203F]+(hp)5[-][/c] [c][3897FF]+(en)17[-][/c]"),
             new ItemSpawner("cup_mead:2", "i_cup_mead", "A mug of mead", @"Effect on use: [c][F4203F]+(hp)5[-][/c] [c][3897FF]+(en)26[-][/c]"),
             new ItemSpawner("cup_mead:3", "i_cup_mead", "A mug of mead", @"Effect on use: [c][F4203F]+(hp)5[-][/c] [c][3897FF]+(en)34[-][/c]"),
             new ItemSpawner("hop_honey:1", "", "Honey beer", @"Effect on use: [c][F4203F]+(hp)10[-][/c] [c][3897FF]+(en)53[-][/c]
             hop_honey_d"),
             new ItemSpawner("hop_honey:2", "", "Honey beer", @"Effect on use: [c][F4203F]+(hp)15[-][/c] [c][3897FF]+(en)65[-][/c]
             hop_honey_d"),
             new ItemSpawner("hop_honey:3", "", "Honey beer", @"Effect on use: [c][F4203F]+(hp)25[-][/c] [c][3897FF]+(en)77[-][/c]
             hop_honey_d"),
             new ItemSpawner("bottle_booz_xxx", "", "Booze", @""),
             new ItemSpawner("bottle_booz_empty", "", "Empty bottle", @""),
             new ItemSpawner("bottle_empty_1", "", "Empty bottle", @""),
             new ItemSpawner("bottle_empty_2", "", "Empty bottle", @""),
             new ItemSpawner("bowl_empty", "", "Empty bowl", @""),
             new ItemSpawner("crab", "", "Crab", @""),
             new ItemSpawner("cup_empty", "", "Empty cup", @""),
             new ItemSpawner("food_empty_plate_1", "", "Empty plate", @""),
             new ItemSpawner("mussels", "", "Mussels", @""),
             new ItemSpawner("nori", "", "Nori", @""),
             new ItemSpawner("pail_dirt", "", "Bucket of dirt", @""),
             new ItemSpawner("pail_braga", "i_pail_dirty_water_2", "Bucket of ferment", @""),
             new ItemSpawner("pail_empty", "", "Empty bucket", @""),
             new ItemSpawner("pail_milk", "", "Bucket of milk", @""),
             new ItemSpawner("butterfly", "", "Butterfly", @""),
             new ItemSpawner("maggot", "", "Maggot", @"Effect on use: [c][3897FF]+(en)2[-][/c]"),
             new ItemSpawner("moth", "", "Moth", @""),
             new ItemSpawner("caldron", "", "Caldron", @""),
             new ItemSpawner("shit", "", "Plate with ...", @""),
             new ItemSpawner("book_ruined_1", "", "Ruined book", @"You can still salvage some paper from it."),
             new ItemSpawner("paper_clean", "i_paper_good", "Clean paper", @""),
             new ItemSpawner("story:1", "i_scroll_story", "Story", @""),
             new ItemSpawner("story:2", "i_scroll_story", "Story", @""),
             new ItemSpawner("story:3", "i_scroll_story", "Story", @""),
             new ItemSpawner("notes:1", "i_note_good", "Notes", @""),
             new ItemSpawner("notes:2", "i_note_good", "Notes", @""),
             new ItemSpawner("notes:3", "i_note_good", "Notes", @""),
             new ItemSpawner("chapter:1", "i_chapter", "Chapter", @""),
             new ItemSpawner("chapter:2", "i_chapter", "Chapter", @""),
             new ItemSpawner("chapter:3", "i_chapter", "Chapter", @""),
             new ItemSpawner("cover:cover_1", "i_cover_1", "Softcover", @""),
             new ItemSpawner("cover:cover_hard:1", "i_cover_hard", "Hard cover", @""),
             new ItemSpawner("cover:cover_hard:2", "i_cover_hard", "Hard cover", @""),
             new ItemSpawner("cover:cover_hard:3", "i_cover_hard", "Hard cover", @""),
             new ItemSpawner("book_soft:1", "i_book_soft_2", "Notebook", @"Strange things are written here..."),
             new ItemSpawner("book_soft:2", "i_book_soft_2", "Notebook", @"Strange things are written here..."),
             new ItemSpawner("book_soft:3", "i_book_soft_2", "Notebook", @""),
             new ItemSpawner("book:book_hard:1", "i_book_soft_2", "Book", @""),
             new ItemSpawner("book:book_hard:2", "i_book_gold_1", "Book", @""),
             new ItemSpawner("book:book_hard:3", "i_book_gold_2", "Book", @""),
             new ItemSpawner("black_paint", "i_vessel_paint_black", "Black paint", @""),
             new ItemSpawner("white_paint", "i_vessel_paint_white", "White paint", @""),
             new ItemSpawner("pen:ink_pen", "i_ink_jar_1", "Pen and ink", @""),
             new ItemSpawner("ink:ink_jar", "i_ink_jar", "Ink", @""),
             new ItemSpawner("flyer:flyer_bad", "i_scroll_white_graph_1", "Flyer", @""),
             new ItemSpawner("skroll_skin_pig", "", "Pigskin paper", @""),
             new ItemSpawner("tanning_agent", "i_flask_tanning_agent", "Tanning agent", @""),
             new ItemSpawner("note_wasted", "", "Wasted note", @""),
             new ItemSpawner("techbook_g_2", "", "Great book (g)", @"Effect on use: [14E549]+(g)50[-][/c]
             Gives 50(g) when used"),
             new ItemSpawner("techbook_b_2", "", "Great  Book (b)", @"Effect on use: [14E549]+(b)50[-][/c]
             Gives 50(b) when used"),
             new ItemSpawner("techbook_r_2", "", "Great  Book (r)", @"Effect on use: [14E549]+(r)50[-][/c]
             Gives 50(r) when used"),
             new ItemSpawner("techbook_g_1", "", "Book (g)", @"Effect on use: [14E549]+(g)25[-][/c]
             Gives 25(g) when used"),
             new ItemSpawner("techbook_b_1", "", "Book (b)", @"Effect on use: [14E549]+(b)25[-][/c]
             Gives 25(b) when used"),
             new ItemSpawner("techbook_r_1", "", "Book (r)", @"Effect on use: [14E549]+(r)25[-][/c]
             Gives 25(r) when used"),
             new ItemSpawner("scroll_blue", "", "Cleric's Beginner's Guide", @"Effect on use: [14E549]+(b)5[-][/c]"),
             new ItemSpawner("scroll_2", "", "Burial certificate", @"Can be sold to the innkeeper."),
             new ItemSpawner("pen_1", "", "Feather", @""),
             new ItemSpawner("test_paper", "", "test_paper", @""),
             new ItemSpawner("test_scroll", "", "test_scroll", @""),
             new ItemSpawner("goo", "", "Goo", @""),
             new ItemSpawner("drop_oil", "", "Oil", @""),
             new ItemSpawner("drop_alcohol", "", "Alcohol", @""),
             new ItemSpawner("alchemy_1_brown", "", "Slowing powder", @""),
             new ItemSpawner("alchemy_1_d_blue", "", "Acceleration powder", @""),
             new ItemSpawner("alchemy_1_d_green", "", "Health powder", @""),
             new ItemSpawner("alchemy_1_d_violet", "", "Death powder", @""),
             new ItemSpawner("alchemy_1_green", "", "Order powder", @""),
             new ItemSpawner("alchemy_1_red", "", "Toxic powder", @""),
             new ItemSpawner("alchemy_1_violet", "", "Chaos powder", @""),
             new ItemSpawner("alchemy_1_yellow", "", "Life powder", @""),
             new ItemSpawner("alchemy_1_yellow_electro", "", "Electric powder", @""),
             new ItemSpawner("taste_booster:alchemy_1_spice", "i_alchemy_1_yellow", "Spices", @""),
             new ItemSpawner("alchemy_2_brown", "", "Slowing solution", @""),
             new ItemSpawner("alchemy_2_d_blue", "", "Acceleration solution", @""),
             new ItemSpawner("alchemy_2_d_green", "", "Health solution", @""),
             new ItemSpawner("alchemy_2_d_violet", "", "Death solution", @""),
             new ItemSpawner("alchemy_2_green", "", "Order solution", @""),
             new ItemSpawner("alchemy_2_red", "", "Toxic solution", @""),
             new ItemSpawner("alchemy_2_violet", "", "Chaos solution", @""),
             new ItemSpawner("alchemy_2_yellow", "", "Life solution", @""),
             new ItemSpawner("alchemy_3_brown", "", "Slowing extract", @""),
             new ItemSpawner("alchemy_3_d_blue", "", "Acceleration extract", @""),
             new ItemSpawner("alchemy_3_d_green", "", "Health extract", @""),
             new ItemSpawner("alchemy_3_d_violet", "", "Death extract", @""),
             new ItemSpawner("alchemy_3_green", "", "Order extract", @""),
             new ItemSpawner("alchemy_3_red", "", "Toxic extract", @""),
             new ItemSpawner("alchemy_3_violet", "", "Chaos extract", @""),
             new ItemSpawner("alchemy_3_yellow", "", "Life extract", @""),
             new ItemSpawner("alchemy_2_empty", "", "Clay cup", @""),
             new ItemSpawner("alchemy_3_empty", "", "Vial", @""),
             new ItemSpawner("goo_alcohol", "", "Alcohol goo", @""),
             new ItemSpawner("goo_ash", "", "Ash goo", @""),
             new ItemSpawner("goo_blood", "", "Blood goo", @""),
             new ItemSpawner("goo_brown", "", "Slowing goo", @""),
             new ItemSpawner("goo_d_blue", "", "Goo of acceleration", @""),
             new ItemSpawner("goo_d_green", "", "Goo of health", @""),
             new ItemSpawner("goo_d_violet", "", "Goo of death", @""),
             new ItemSpawner("goo_diamond", "", "Diamond goo", @""),
             new ItemSpawner("goo_gold", "", "Gold goo", @""),
             new ItemSpawner("goo_graphite", "", "Graphite goo", @""),
             new ItemSpawner("goo_green", "", "Goo or order", @""),
             new ItemSpawner("goo_oil", "", "Oil goo", @""),
             new ItemSpawner("goo_red", "", "Toxic goo", @""),
             new ItemSpawner("goo_salt", "", "Salt goo", @""),
             new ItemSpawner("goo_silver", "", "Silver goo", @""),
             new ItemSpawner("goo_spice", "", "Spice goo", @""),
             new ItemSpawner("goo_violet", "", "Goo of chaos", @""),
             new ItemSpawner("goo_water", "", "Water goo", @""),
             new ItemSpawner("goo_white", "", "White goo", @""),
             new ItemSpawner("goo_yellow", "", "Goo of life", @""),
             new ItemSpawner("goo_yellow_electro", "", "Electric goo", @""),
             new ItemSpawner("zombie_juise", "i_pot_zombie_rise", "Zombie juice", @""),
             new ItemSpawner("grave_top_wd_tab_1", "", "Wooden marker", @"Adds (wr)1 to the grave."),
             new ItemSpawner("grave_top_wd_cross_1", "", "Wooden cross", @"Adds (wr)2 to the grave."),
             new ItemSpawner("grave_bot_wd_1", "", "Wooden grave fence", @"Adds (wr)1 to the grave."),
             new ItemSpawner("grave_top_stn_plate_1", "", "Gravestone", @"Adds (wr)2 to the grave."),
             new ItemSpawner("grave_bot_stn_1", "", "Stone grave fence", @"Adds (wr)2 to the grave."),
             new ItemSpawner("grave_top_stn_cross_1", "", "Stone cross", @"Adds (wr)3 to the grave."),
             new ItemSpawner("grave_top_stn_plate_2", "", "Gravestone II", @"Adds (wr)3 to the grave."),
             new ItemSpawner("grave_bot_stn_2", "", "Stone grave fence II", @"Adds (wr)3 to the grave."),
             new ItemSpawner("grave_top_stn_cross_2", "", "Stone cross II", @"Adds (wr)4 to the grave."),
             new ItemSpawner("grave_top_stella_stn_1", "", "Stone plinth", @"Adds (wr)4 to the grave."),
             new ItemSpawner("grave_top_sculpt_stn_1", "", "Stone sculpture", @"Adds (wr)5 to the grave."),
             new ItemSpawner("grave_top_sculpt_stn_2", "", "Stone sculpture II", @"Adds (wr)5 to the grave."),
             new ItemSpawner("grave_bot_mrb_1", "", "Marble grave fence", @"Adds (wr)4 to the grave."),
             new ItemSpawner("grave_top_mrb_cross_1", "", "Marble cross", @"Adds (wr)5 to the grave."),
             new ItemSpawner("grave_bot_mrb_2", "", "Marble grave fence II", @"Adds (wr)5 to the grave."),
             new ItemSpawner("grave_top_mrb_cross_2", "", "Marble cross II", @"Adds (wr)6 to the grave."),
             new ItemSpawner("grave_top_stella_mrb_1", "", "Marble plinth", @"Adds (wr)6 to the grave."),
             new ItemSpawner("grave_top_sarcofag_mrb_1", "", "Marble sarcophagus", @"Adds (wr)10 to the grave."),
             new ItemSpawner("grave_top_sculpt_mrb_1", "", "Marble sculpture", @"Adds (wr)7 to the grave."),
             new ItemSpawner("grave_top_sculpt_mrb_2", "", "Marble sculpture II", @"Adds (wr)7 to the grave."),
             new ItemSpawner("grave_bot_mrb_3", "", "Marble grave fence III", @"Adds (wr)5 to the grave."),
             new ItemSpawner("grave_bot_mrb_4", "", "Marble grave fence IV", @"Adds (wr)6 to the grave."),
             new ItemSpawner("grave_bot_mrb_5", "", "Marble grave fence V", @"Adds (wr)7 to the grave."),
             new ItemSpawner("grave_bot_stn_3", "", "Stone grave fence III", @"Adds (wr)3 to the grave."),
             new ItemSpawner("grave_bot_stn_4", "", "Stone grave fence IV", @"Adds (wr)4 to the grave."),
             new ItemSpawner("grave_bot_stn_5", "", "Stone grave fence V", @"Adds (wr)5 to the grave."),
             new ItemSpawner("grave_top_highangel_mrb_1", "", "Marble sculpture IV", @"Adds (wr)9 to the grave."),
             new ItemSpawner("grave_top_highangel_stn_1", "", "Stone sculpture IV", @"Adds (wr)7 to the grave."),
             new ItemSpawner("grave_top_memorial_mrb_1", "", "Marble Gravestone III", @"Adds (wr)6 to the grave."),
             new ItemSpawner("grave_top_memorial_stn_1", "", "Gravestone III", @"Adds (wr)4 to the grave."),
             new ItemSpawner("grave_top_womansaver_mrb_1", "", "Marble sculpture III", @"Adds (wr)8 to the grave."),
             new ItemSpawner("grave_top_womansaver_stn_1", "", "Stone sculpture III", @"Adds (wr)6 to the grave."),
             new ItemSpawner("recipe_advanced_gravestones", "", "Recipe: Advanced gravestones", @""),
             new ItemSpawner("recipe_advanced_gravestones_2", "", "Recipe: Advanced gravestones II", @""),
             new ItemSpawner("recipe_stone_statues", "", "Recipe: Stone statues", @""),
             new ItemSpawner("recipe_marble_statues", "", "Recipe: Marble statues", @""),
             new ItemSpawner("recipe_marble_fences", "", "Recipe: Marble fences", @""),
             new ItemSpawner("pot_heal", "", "Heal potion", @"Effect on use: [c][F4203F]+(hp)50[-][/c]"),
             new ItemSpawner("pot_mana", "", "Energy potion", @"Effect on use: [c][3897FF]+(en)50[-][/c]"),
             new ItemSpawner("pot_sweat", "", "Stomach Relief", @""),
             new ItemSpawner("pot_appetite", "i_pot_green", "Digestion potion", @"Effect on use: [c][C16000]Digestion potion[-][/c] (Food gives you more (en).)
             Food gives you more (en)."),
             new ItemSpawner("pot_speed", "i_pot_green_d", "Speed potion", @"Effect on use: [c][C16000]Speed potion[-][/c]
             Increases your speed."),
             new ItemSpawner("pot_heal_long", "i_pot_vioet", "Restoring potion", @"Effect on use: [c][C16000]Restoring potion[-][/c] (Restore your (hp) over time.)
             Restore your (hp) over time."),
             new ItemSpawner("pot_damage", "i_pot_yellow", "Rage potion", @"Effect on use: [c][C16000]Rage potion[-][/c] (You deal additional damage to monsters.)
             You deal additional damage to monsters."),
             new ItemSpawner("pot_berserk", "i_pot_black", "Berserk potion", @"Effect on use: [c][C16000]Berserk[-][/c]
             You deal a lot of damage but also lose (hp) over time."),
             new ItemSpawner("pot_armor", "i_pot_yellow_d", "Protection potion", @"Effect on use: [c][C16000]Protection potion[-][/c] (Incoming damage reduced.)
             Incoming damage reduced."),
             new ItemSpawner("coins", "", "Coins", @""),
             new ItemSpawner("flour", "", "Flour", @""),
             new ItemSpawner("permission", "", "Exhumation Permission", @""),
             new ItemSpawner("building_permission", "i_scroll_white_bp", "Building permission", @""),
             new ItemSpawner("rightful_citizen_paper", "i_scroll_white_3", "Rightful Citizen papers", @""),
             new ItemSpawner("flw_chamomile", "", "White flower", @"Effect on use: [c][3897FF]+(en)3[-][/c]"),
             new ItemSpawner("flw_dandelion", "", "Yellow flower", @"Effect on use: [c][3897FF]+(en)3[-][/c]"),
             new ItemSpawner("flw_poppy", "", "Red flower", @"Effect on use: [c][3897FF]+(en)3[-][/c]"),
             new ItemSpawner("raw_stone", "", "Raw stone", @""),
             new ItemSpawner("stone_plate", "", "Stone plate", @""),
             new ItemSpawner("cobblestone", "", "Cobblestone", @""),
             new ItemSpawner("preach_1", "", "preach_1", @"(cross)0 needed to guarantee a successful ceremony."),
             new ItemSpawner("preach_2", "", "preach_2", @"(cross)0 needed to guarantee a successful ceremony."),
             new ItemSpawner("b_empty", "i_b_empty", "Casual prayer", @"(cross)10 needed to guarantee a successful ceremony.
             A couple words without any real inspiration. It still works somehow..."),
             new ItemSpawner("b_faith:1", "i_b_faith", "Prayer for faith", @"(cross)10 needed to guarantee a successful ceremony.
             A number of very touching words. Your flock will produce more (faith)."),
             new ItemSpawner("b_faith:2", "i_b_faith", "Prayer for faith", @"(cross)20 needed to guarantee a successful ceremony.
             A number of very touching words. Your flock will produce more (faith)."),
             new ItemSpawner("b_faith:3", "i_b_faith", "Prayer for faith", @"(cross)50 needed to guarantee a successful ceremony.
             A number of very touching words. Your flock will produce more (faith)."),
             new ItemSpawner("b_faith_money:1", "i_b_faith_money", "Combo prayer", @"(cross)15 needed to guarantee a successful ceremony.
             A touching story about the church's needs. Earns extra (faith) and donations."),
             new ItemSpawner("b_faith_money:2", "i_b_faith_money", "Combo prayer", @"(cross)30 needed to guarantee a successful ceremony.
             A touching story about the church's needs. Earns extra (faith) and donations."),
             new ItemSpawner("b_faith_money:3", "i_b_faith_money", "Combo prayer", @"(cross)60 needed to guarantee a successful ceremony.
             A touching story about the church's needs. Earns extra (faith) and donations."),
             new ItemSpawner("b_money:1", "i_b_money", "Prayer for donations", @"(cross)10 needed to guarantee a successful ceremony.
             Piteous word about the church's needs. You can count on extra donations!"),
             new ItemSpawner("b_money:2", "i_b_money", "Prayer for donations", @"(cross)20 needed to guarantee a successful ceremony.
             Piteous word about the church's needs. You can count on extra donations!"),
             new ItemSpawner("b_money:3", "i_b_money", "Prayer for donations", @"(cross)50 needed to guarantee a successful ceremony.
             Piteous word about the church's needs. You can count on extra donations!"),
             new ItemSpawner("b_plant:1", "i_b_plant", "Prayer for shoots and roots", @"(cross)10 needed to guarantee a successful ceremony.
             A few words about the importance of agriculture, fertilization, and personal hygiene."),
             new ItemSpawner("b_plant:2", "i_b_plant", "Prayer for shoots and roots", @"(cross)20 needed to guarantee a successful ceremony.
             A few words about the importance of agriculture, fertilization, and personal hygiene."),
             new ItemSpawner("b_plant:3", "i_b_plant", "Prayer for shoots and roots", @"(cross)30 needed to guarantee a successful ceremony.
             A few words about the importance of agriculture, fertilization, and personal hygiene."),
             new ItemSpawner("b_shield:1", "i_b_shield", "Prayer for protection", @"(cross)10 needed to guarantee a successful ceremony.
             True words that will make you tough."),
             new ItemSpawner("b_shield:2", "i_b_shield", "Prayer for protection", @"(cross)20 needed to guarantee a successful ceremony.
             True words that will make you tough."),
             new ItemSpawner("b_shield:3", "i_b_shield", "Prayer for protection", @"(cross)40 needed to guarantee a successful ceremony.
             True words that will make you tough."),
             new ItemSpawner("b_sins:1", "i_b_sins", "Prayer for repentance", @"(cross)10 needed to guarantee a successful ceremony.
             It's about sin and forgiveness. Based on a couple of stories from your youth."),
             new ItemSpawner("b_sins:2", "i_b_sins", "Prayer for repentance", @"(cross)20 needed to guarantee a successful ceremony.
             It's about sin and forgiveness. Based on a couple of stories from your youth."),
             new ItemSpawner("b_sins:3", "i_b_sins", "Prayer for repentance", @"(cross)40 needed to guarantee a successful ceremony.
             It's about sin and forgiveness. Based on a couple of stories from your youth."),
             new ItemSpawner("b_skull:1", "i_b_skull", "Prayer for repose", @"(cross)20 needed to guarantee a successful ceremony.
             (Advertising) All deceased are welcome in your graveyard!"),
             new ItemSpawner("b_skull:2", "i_b_skull", "Prayer for repose", @"(cross)40 needed to guarantee a successful ceremony.
             (Advertising) All deceased are welcome in your graveyard!"),
             new ItemSpawner("b_skull:3", "i_b_skull", "Prayer for repose", @"(cross)50 needed to guarantee a successful ceremony.
             (Advertising) All deceased are welcome in your graveyard!"),
             new ItemSpawner("b_sword:1", "i_b_sword", "Prayer for retribution", @"(cross)10 needed to guarantee a successful ceremony.
             True words that fill you with fury."),
             new ItemSpawner("b_sword:2", "i_b_sword", "Prayer for retribution", @"(cross)20 needed to guarantee a successful ceremony.
             True words that fill you with fury."),
             new ItemSpawner("b_sword:3", "i_b_sword", "Prayer for retribution", @"(cross)40 needed to guarantee a successful ceremony.
             True words that fill you with fury."),
             new ItemSpawner("b_village:1", "i_b_vilage", "Prayer for prosperity", @"(cross)10 needed to guarantee a successful ceremony.
             For those who earn their keep in honest trade. This will give you a [c][bb5c1c]Commercial Blessing[-][/c] which can improve one vendor."),
             new ItemSpawner("b_village:2", "i_b_vilage", "Prayer for prosperity", @"(cross)20 needed to guarantee a successful ceremony.
             For those who earn their keep in honest trade. This will give you a [c][bb5c1c]Commercial Blessing[-][/c] which can improve one vendor."),
             new ItemSpawner("b_village:3", "i_b_vilage", "Prayer for prosperity", @"(cross)30 needed to guarantee a successful ceremony.
             For those who earn their keep in honest trade. This will give you a [c][bb5c1c]Commercial Blessing[-][/c] which can improve one vendor."),
             new ItemSpawner("b_pen:1", "i_b_pen", "Prayer for imagination", @"(cross)10 needed to guarantee a successful ceremony.
             These words will boost your inspiration!"),
             new ItemSpawner("b_pen:2", "i_b_pen", "Prayer for imagination", @"(cross)40 needed to guarantee a successful ceremony.
             These words will boost your inspiration!"),
             new ItemSpawner("b_pen:3", "i_b_pen", "Prayer for imagination", @"(cross)60 needed to guarantee a successful ceremony.
             These words will boost your inspiration!"),
             new ItemSpawner("b_star:1", "i_b_star", "Prayer for excellence", @"(cross)10 needed to guarantee a successful ceremony.
             True words about the blessedness of hard work."),
             new ItemSpawner("b_star:2", "i_b_star", "Prayer for excellence", @"(cross)40 needed to guarantee a successful ceremony.
             True words about the blessedness of hard work."),
             new ItemSpawner("b_star:3", "i_b_star", "Prayer for excellence", @"(cross)60 needed to guarantee a successful ceremony.
             True words about the blessedness of hard work."),
             new ItemSpawner("b_circle:1", "i_b_circle", "", @"(cross)0 needed to guarantee a successful ceremony."),
             new ItemSpawner("b_circle:2", "i_b_circle", "", @"(cross)0 needed to guarantee a successful ceremony."),
             new ItemSpawner("b_circle:3", "i_b_circle", "", @"(cross)0 needed to guarantee a successful ceremony."),
             new ItemSpawner("b_techpoint_blue:1", "i_b_techpoint_blue", "", @"(cross)0 needed to guarantee a successful ceremony."),
             new ItemSpawner("b_techpoint_blue:2", "i_b_techpoint_blue", "", @"(cross)0 needed to guarantee a successful ceremony."),
             new ItemSpawner("b_techpoint_blue:3", "i_b_techpoint_blue", "", @"(cross)0 needed to guarantee a successful ceremony."),
             new ItemSpawner("b_techpoint_green:1", "i_b_techpoint_green", "", @"(cross)0 needed to guarantee a successful ceremony."),
             new ItemSpawner("b_techpoint_green:2", "i_b_techpoint_green", "", @"(cross)0 needed to guarantee a successful ceremony."),
             new ItemSpawner("b_techpoint_green:3", "i_b_techpoint_green", "", @"(cross)0 needed to guarantee a successful ceremony."),
             new ItemSpawner("b_techpoint_red:1", "i_b_techpoint_red", "", @"(cross)0 needed to guarantee a successful ceremony."),
             new ItemSpawner("b_techpoint_red:2", "i_b_techpoint_red", "", @"(cross)0 needed to guarantee a successful ceremony."),
             new ItemSpawner("b_techpoint_red:3", "i_b_techpoint_red", "", @"(cross)0 needed to guarantee a successful ceremony."),
             new ItemSpawner("b_random:1", "i_b_random", "", @"(cross)0 needed to guarantee a successful ceremony."),
             new ItemSpawner("b_random:2", "i_b_random", "", @"(cross)0 needed to guarantee a successful ceremony."),
             new ItemSpawner("b_random:3", "i_b_random", "", @"(cross)0 needed to guarantee a successful ceremony."),
             new ItemSpawner("b_ghost:1", "i_b_ghost", "", @"(cross)0 needed to guarantee a successful ceremony."),
             new ItemSpawner("b_ghost:2", "i_b_ghost", "", @"(cross)0 needed to guarantee a successful ceremony."),
             new ItemSpawner("b_ghost:3", "i_b_ghost", "", @"(cross)0 needed to guarantee a successful ceremony."),
             new ItemSpawner("b_cross:1", "i_b_cross", "", @"(cross)0 needed to guarantee a successful ceremony."),
             new ItemSpawner("b_cross:2", "i_b_cross", "", @"(cross)0 needed to guarantee a successful ceremony."),
             new ItemSpawner("b_cross:3", "i_b_cross", "", @"(cross)0 needed to guarantee a successful ceremony."),
             new ItemSpawner("b_energy:1", "i_b_energy", "", @"(cross)0 needed to guarantee a successful ceremony."),
             new ItemSpawner("b_energy:2", "i_b_energy", "", @"(cross)0 needed to guarantee a successful ceremony."),
             new ItemSpawner("b_energy:3", "i_b_energy", "", @"(cross)0 needed to guarantee a successful ceremony."),
             new ItemSpawner("body", "", "Body", @""),
             new ItemSpawner("body_guard", "i_body", "body_guard", @""),
             new ItemSpawner("unknown_body_part", "", "Unknown body part", @""),
             new ItemSpawner("skull", "i_skull", "Skull", @""),
             new ItemSpawner("bone", "i_bone", "Bone", @""),
             new ItemSpawner("flesh", "i_flesh", "Flesh", @""),
             new ItemSpawner("fat", "i_fat", "Fat", @""),
             new ItemSpawner("blood", "i_blood", "Blood", @""),
             new ItemSpawner("skin", "i_skin", "Skin", @""),
             new ItemSpawner("brain_dark", "", "Dark brain", @""),
             new ItemSpawner("heart_dark", "", "Dark heart", @""),
             new ItemSpawner("intestine_dark", "", "Dark intestines", @""),
             new ItemSpawner("lungs_dark", "", "Dark lungs", @""),
             new ItemSpawner("brain:brain_0_0", "i_brain", "Brain", @""),
             new ItemSpawner("brain:brain_1_1", "i_brain", "Brain", @""),
             new ItemSpawner("brain:brain_2_-1", "i_brain", "Brain", @""),
             new ItemSpawner("brain:brain_0_2", "i_brain", "Brain", @""),
             new ItemSpawner("brain:brain_2_0", "i_brain", "Brain", @""),
             new ItemSpawner("brain:brain_0_1", "i_brain", "Brain", @""),
             new ItemSpawner("brain:brain_2_1", "i_brain", "Brain", @""),
             new ItemSpawner("brain:brain_2_2", "i_brain", "Brain", @""),
             new ItemSpawner("brain:brain_-2_3", "i_brain", "Brain", @""),
             new ItemSpawner("brain:brain_4_1", "i_brain", "Brain", @""),
             new ItemSpawner("brain:brain_3_3", "i_brain", "Brain", @""),
             new ItemSpawner("heart:heart_0_0", "i_heart", "Heart", @""),
             new ItemSpawner("heart:heart_1_1", "i_heart", "Heart", @""),
             new ItemSpawner("heart:heart_2_-1", "i_heart", "Heart", @""),
             new ItemSpawner("heart:heart_0_2", "i_heart", "Heart", @""),
             new ItemSpawner("heart:heart_2_0", "i_heart", "Heart", @""),
             new ItemSpawner("heart:heart_0_1", "i_heart", "Heart", @""),
             new ItemSpawner("heart:heart_2_1", "i_heart", "Heart", @""),
             new ItemSpawner("heart:heart_2_2", "i_heart", "Heart", @""),
             new ItemSpawner("heart:heart_-2_3", "i_heart", "Heart", @""),
             new ItemSpawner("heart:heart_4_1", "i_heart", "Heart", @""),
             new ItemSpawner("heart:heart_3_3", "i_heart", "Heart", @""),
             new ItemSpawner("intestine:intestine_0_0", "i_intestine", "Intestines", @""),
             new ItemSpawner("intestine:intestine_1_1", "i_intestine", "Intestines", @""),
             new ItemSpawner("intestine:intestine_2_-1", "i_intestine", "Intestines", @""),
             new ItemSpawner("intestine:intestine_0_2", "i_intestine", "Intestines", @""),
             new ItemSpawner("intestine:intestine_2_0", "i_intestine", "Intestines", @""),
             new ItemSpawner("intestine:intestine_0_1", "i_intestine", "Intestines", @""),
             new ItemSpawner("intestine:intestine_2_1", "i_intestine", "Intestines", @""),
             new ItemSpawner("intestine:intestine_2_2", "i_intestine", "Intestines", @""),
             new ItemSpawner("intestine:intestine_-2_3", "i_intestine", "Intestines", @""),
             new ItemSpawner("intestine:intestine_4_1", "i_intestine", "Intestines", @""),
             new ItemSpawner("intestine:intestine_3_3", "i_intestine", "Intestines", @""),
             new ItemSpawner("organs:organs_1", "i_organs", "Organs", @""),
             new ItemSpawner("surgeon_mistake", "i_surgeon_mistake", "Surgeon's mistake", @"Your inexperience shows. — The surgery didn't go very well. You've made a mess of the body, lowering its quality."),
             new ItemSpawner("lungs:lungs_1", "", "Lungs", @""),
             new ItemSpawner("scalp", "", "Scalp", @""),
             new ItemSpawner("face", "", "Face", @""),
             new ItemSpawner("tongue", "", "Tongue", @""),
             new ItemSpawner("eye", "", "Eye", @""),
             new ItemSpawner("ribs", "", "Ribs", @""),
             new ItemSpawner("pelvis", "", "Pelvis", @""),
             new ItemSpawner("liver", "", "Liver", @""),
             new ItemSpawner("kidneys", "i_bud", "Kidneys", @""),
             new ItemSpawner("bud", "", "Kidneys", @""),
             new ItemSpawner("humerus", "", "Humerus", @""),
             new ItemSpawner("forearm", "", "Forearm", @""),
             new ItemSpawner("hand", "", "Hand", @""),
             new ItemSpawner("muscle", "", "Muscle", @""),
             new ItemSpawner("human flesh", "", "Human flesh", @""),
             new ItemSpawner("human blood", "", "Human blood", @""),
             new ItemSpawner("embalm_1_1", "i_jar_blue", "Lye injection", @"This liquid can be applied to a body on the embalming table to modify its characteristics."),
             new ItemSpawner("embalm_2_0", "i_jar_dark", "Dark injection", @"This liquid can be applied to a body on the embalming table to modify its characteristics."),
             new ItemSpawner("embalm_0_1", "i_jar_green_l", "Glue injection", @"This liquid can be applied to a body on the embalming table to modify its characteristics."),
             new ItemSpawner("embalm_stop", "i_jar_green_l_cross", "Preservative injection", @"This embalming fluid halts the body's decay."),
             new ItemSpawner("embalm_50", "i_jar_green_l_plus", "Restore injection", @"This embalming fluid reduces body's decay by 50%."),
             new ItemSpawner("embalm_-1_1", "i_jar_pink", "Silver injection", @"This liquid can be applied to a body on the embalming table to modify its characteristics."),
             new ItemSpawner("embalm_-2_2", "i_jar_pink_star_gold", "Gold injection", @"This liquid can be applied to a body on the embalming table to modify its characteristics."),
             new ItemSpawner("embalm_-1_-1", "i_jar_yellow", "Acid injection", @"This liquid can be applied to a body on the embalming table to modify its characteristics."),
             new ItemSpawner("glue", "i_flask_glue", "Glue", @""),
             new ItemSpawner("dark_elixir", "i_flask_dark_elixir", "Dark Elixir", @""),
             new ItemSpawner("alkali", "i_flask_alkali", "Alkali", @""),
             new ItemSpawner("acid", "i_flask_acid", "Acid", @""),
             new ItemSpawner("flask_green_l_plus", "", "Balsamic solution", @""),
             new ItemSpawner("preservative", "i_flask_preservative", "Preservative", @""),
             new ItemSpawner("silver_elixir", "i_flask_pink", "Silver Elixir", @""),
             new ItemSpawner("golden_elixir", "i_flask_pink_star_gold", "Golden Elixir", @""),
             new ItemSpawner("test_paper:1", "i_scroll_clear_1", "test_paper:1", @"test_paper_d"),
             new ItemSpawner("test_paper:2", "i_scroll_clear_1", "test_paper:2", @"test_paper_d"),
             new ItemSpawner("test_paper:3", "i_scroll_clear_1", "test_paper:3", @"test_paper_d"),
             new ItemSpawner("test_scroll:1", "i_scroll_1", "test_scroll:1", @"test_scroll_d"),
             new ItemSpawner("test_scroll:2", "i_scroll_1", "test_scroll:2", @"test_scroll_d"),
             new ItemSpawner("test_scroll:3", "i_scroll_1", "test_scroll:3", @"test_scroll_d"),
             new ItemSpawner("pseudo_item_qual_2", "", "pseudo_item_qual_2", @""),
             new ItemSpawner("pseudo_item_qual_4", "", "pseudo_item_qual_4", @""),
             new ItemSpawner("pseudo_item_qual_10", "", "pseudo_item_qual_10", @""),
             new ItemSpawner("nitroglycerine", "i_retort_black", "", @""),
             new ItemSpawner("recipe_Pies", "i_scroll_recipe_pie", "Recipe: Pies", @""),
             new ItemSpawner("recipe_Veg", "i_scroll_recipe_pumpkin", "Recipe: Tasty and Healthy", @""),
             new ItemSpawner("recipe_Sweet", "i_scroll_recipe_croissant", "Recipe: Sweet baking", @""),
             new ItemSpawner("recipe_delicacies", "i_scroll_recipe_fish", "Recipe: Fish delicacies", @""),
             new ItemSpawner("recipe_Jelly", "i_scroll_recipe_jelly", "Recipe: Jelly", @""),
             new ItemSpawner("recipe_2min", "i_scroll_recipe_apple", "Recipe: Simple and tasty", @""),
             new ItemSpawner("recipe_honey", "i_scroll_recipe_beer", "Recipe: Special beer", @""),
             new ItemSpawner("hearthstone", "", "Teleportstone", @""),
             new ItemSpawner("teleport_scroll", "", "Scroll of teleportation", @"Nothing fancy, just a way to get around. Alas, disposable."),
             new ItemSpawner("recipe_pot_speed", "i_scroll_white_graph_2", "Recipe: Speed potion", @""),
             new ItemSpawner("refugee_happiness_item", "i_refugee_happiness_item", "Refugee Happiness", @""),
             new ItemSpawner("refugee_happiness_slot_item", "i_goc_tent_slot", "Camp Quality", @""),
             new ItemSpawner("refugee_tent_place_available_item", "i_refugee_tent_place_available_item", "The free place", @""),
             new ItemSpawner("refugee_tent_place_busy_item", "i_refugee_tent_place_busy_item", "The busy place", @""),
             new ItemSpawner("donkey_lock_wool", "i_donkey_lock_wool", "Piece of donkey hair", @"Smells of sweat, carrots, and communism."),
             new ItemSpawner("garlic_bunch", "i_garlic_bunch", "Bunch of garlic", @"Effect on use: [c][C16000]Eaten garlic[-][/c] (Your mouth is burning!)
             Effective against vampires... and friends alike."),
             new ItemSpawner("vampire_jaw", "i_vampire_jaw", "Vampire's jaw", @"You're almost ready for Halloween."),
             new ItemSpawner("vampire_sunscreen", "i_vampire_sunscreen", "Sun cream for vampires", @"Adequate evidence of a vampire's demise. At least, according to Alaric."),
             new ItemSpawner("memory_potion_receipt", "i_memory_potion_receipt", "Memory tincture recipe", @"Now you can brew up a Memory tincture. 1% alcohol, 99% bubbles."),
             new ItemSpawner("book_of_receipts", "i_book_of_receipts", "Cookbook", @"50 ways to cook ratatouille with vegetables and cats."),
             new ItemSpawner("skeleton_leg", "i_skeleton_leg", "Bone leg", @"Short and curved. Clearly wasn't cut out to be a ballerina."),
             new ItemSpawner("vampires_blackened_boot", "i_vampires_blackened_boot", "Сharred vampire shoe", @"Got of lucky compared with its owner."),
             new ItemSpawner("witchers_eye", "i_witchers_eye", "Witcher's Eye", @"Delivers its bearer visions of the past. Cranky. Only works when it wants to."),
             new ItemSpawner("memory_potion", "i_memory_potion", "Memory tincture", @"Unstable, unreliable, unbearable. Spray it in both eyes."),
             new ItemSpawner("details_pile", "i_details_pile", "Pile of components", @"Suspiciously reminiscent of a pile of common scrap."),
             new ItemSpawner("memory_powder", "i_memory_powder", "Memory powder", @""),
             new ItemSpawner("pagan_amulet", "i_pagan_amulet", "Pagan amulet of spirit summoning", @""),
             new ItemSpawner("scroll_ghoul", "i_scroll_ghoul", "Scroll of ghoul raising", @"A page ripped from the Necronomicon. Written in blood."),
             new ItemSpawner("dark_gold_cloak", "i_dark_gold_cloak", "Black and gold cloak", @""),
             new ItemSpawner("death_emulsion", "i_death_emulsion", "Emulsion Of Death", @"It tastes like ordinary milk. Mixed with gasoline and chili pepper."),
             new ItemSpawner("unicorn_horn", "i_unicorn_horn", "Iron unicorn horns", @"Awaken your internal unicorn! Rainbows not included."),
             new ItemSpawner("jelly_splinter", "i_jelly_splinter", "Jelly of Incredible Power", @"A biologically active additive. No responsibility for the consequences."),
             new ItemSpawner("magic_pumpkin", "i_magic_pumpkin", "Magic pumpkin", @"Well aren't you the fairy godmother! Well, fairy godfather."),
             new ItemSpawner("first_letter", "i_first_letter", "Revolutionary message №1", @""),
             new ItemSpawner("second_letter", "i_first_letter", "Revolutionary message №2", @""),
             new ItemSpawner("third_letter", "i_first_letter", "Revolutionary message №3", @""),
             new ItemSpawner("revolutionary_banner", "i_revolutionary_banner", "Revolutionary donkey banner", @"Thank God they didn't ask for 'The Donkey Internationale'!"),
             new ItemSpawner("battle_horseshoes", "i_battle_horseshoes", "Battle horseshoes", @"Hardened and studded. All the better for your kicking pleasure!"),
             new ItemSpawner("bank_check", "i_goc_bank_check", "Bank checks", @"You've never seen so many zeros! Unfortunately, the checks are personalized."),
             new ItemSpawner("carl_bounded", "i_carl_bounded_drop", "Bound Carl", @""),
             new ItemSpawner("aphorisms", "i_goc_bank_check", "Aphorisms about the evils of money", @"They're readable. Not masterpieces, but written with feeling."),
             new ItemSpawner("note_from_unknown_1", "i_scroll_3", "Note from unknown", @""),
             new ItemSpawner("note_from_unknown_2", "i_scroll_3", "Note from unknown", @""),
             new ItemSpawner("note_from_unknown_3", "i_scroll_3", "Note from unknown", @""),
             new ItemSpawner("bag_alchemy", "i_goc_bag_1_alchemy", "Alchemist's bag", @""),
             new ItemSpawner("bag_farming", "i_goc_bag_1_farmer", "Farmer's bag", @""),
             new ItemSpawner("bag_fishing", "i_goc_bag_1_fisher", "Fisherman's bag", @""),
             new ItemSpawner("bag_tools", "i_goc_bag_1_tools", "Tool bag", @""),
             new ItemSpawner("bag_potions", "i_goc_bag_2_pots", "Potion bag", @""),
             new ItemSpawner("bag_builder", "i_goc_bag_2_builder", "Builder's bag", @""),
             new ItemSpawner("bag_food", "i_goc_bag_2_food", "Food bag", @""),
             new ItemSpawner("bag_universal", "i_goc_bag_1", "Universal bag", @""),
             new ItemSpawner("bag_universal_big", "i_goc_bag_2", "Big universal bag", @""),
             new ItemSpawner("recipe_bag_alchemy", "", "Recipe: Alchemist's bag", @""),
             new ItemSpawner("recipe_bag_farming", "", "Recipe: Farmer's bag", @""),
             new ItemSpawner("recipe_bag_fishing", "", "Recipe: Fisherman's bag", @""),
             new ItemSpawner("recipe_bag_tools", "", "Recipe: Tool bag", @""),
             new ItemSpawner("recipe_bag_potions", "", "Recipe: Potion bag", @""),
             new ItemSpawner("recipe_bag_builder", "", "Recipe: Builder's bag", @""),
             new ItemSpawner("recipe_bag_food", "", "Recipe: Food bag", @""),
             new ItemSpawner("recipe_bag_universal", "i_scroll_graph_2", "Recipe: Universal bag", @""),
             new ItemSpawner("recipe_bag_universal_big", "i_scroll_graph_3", "Recipe: Big universal bag", @"")};
             
             return lst;
        }
    }
}
