using System;
using System.IO;
using UnityEngine;

namespace Doorstop
{
    public static class Loader
    {
        public static void Main(string[] args)
        {
            GUI.Label(new Rect(50, 50, 100, 20), "Hello World!");

            using (TextWriter tw = File.CreateText("doorstop_is_alive.txt"))
            {
                tw.WriteLine($"Hello! This text file was generated by Doorstop on {DateTime.Now:R}!");
                tw.WriteLine($"Command line: {Environment.CommandLine}");

                tw.WriteLine();
                tw.WriteLine("Doorstop also set the following environment variables:");
                tw.WriteLine($"DOORSTOP_INVOKE_PATH = {Environment.GetEnvironmentVariable("DOORSTOP_INVOKE_DLL_PATH")}");
                tw.WriteLine($"DOORSTOP_MANAGED_FOLDER_DIR = {Environment.GetEnvironmentVariable("DOORSTOP_MANAGED_FOLDER_DIR")}");
                tw.WriteLine($"DOORSTOP_PROCESS_PATH = {Environment.GetEnvironmentVariable("DOORSTOP_PROCESS_PATH")}");

                tw.WriteLine("Replace this DLL with a custom-made one to do whatever you want!");

                tw.Flush();
            }
            // var zf = new ZomboForm.ZomboForm();
            // zf.Show(default);
            // if (GUI.Button(new Rect(10, 10, 150, 100), "I am a button"))
            // {
            //     
            // }
        }
        
        // public void OnGUI()
        // {
        //     GUI.Label(new Rect(10, 10, 100, 20), "Hello World!");
        // }
    }
}